[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "production_entry"
version = "0.0.3"
authors = [
    {name = "Your Company", email = "info@yourcompany.com"}
]
description = "Production Planning and Queuing System for Manufacturing Units"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.urls]
Home = "https://github.com/Dharshantfs/production_entry"

[tool.setuptools.packages.find]
where = ["."]
include = ["production_entry*"]

[tool.bench.dev-dependencies]

