import re

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import cint, flt, getdate, nowtime, today

from production_entry.production_planning.doctype.planning_sheet.planning_sheet import (
	extract_quality_and_color,
)


def batch_shift_value(shift: str | None) -> str:
	if not shift:
		return ""
	s = shift.lower()
	if "night" in s:
		return "Night"
	if "day" in s:
		return "Day"
	return shift


def _cstr(v) -> str:
	return str(v).strip() if v is not None else ""


def _spr_row_get(spr_row, key: str):
	if spr_row is None:
		return None
	if isinstance(spr_row, dict):
		return spr_row.get(key)
	return spr_row.get(key)


def _batch_field_net_weight_kgs(batch_meta) -> str | None:
	for df in batch_meta.fields:
		lab = (df.label or "").lower()
		if "net" in lab and "weight" in lab:
			return df.fieldname
	for fn in ("custom_net_weight_kgs", "custom_net_weight", "net_weight_kgs"):
		if batch_meta.has_field(fn):
			return fn
	return None


def _batch_field_gross_weight_kgs(batch_meta) -> str | None:
	for df in batch_meta.fields:
		lab = (df.label or "").lower()
		if "gross" in lab and "weight" in lab:
			return df.fieldname
	for fn in ("custom_gross_weight_kgs", "custom_gross_weight", "gross_weight_kgs"):
		if batch_meta.has_field(fn):
			return fn
	return None


def _batch_field_length_mtrs(batch_meta) -> str | None:
	for df in batch_meta.fields:
		lab = (df.label or "").lower()
		if "planned qty" in lab:
			continue
		if "length" in lab and ("mtr" in lab or "meter" in lab or "mtrs" in lab):
			return df.fieldname
		if "ordered" in lab and "length" in lab:
			return df.fieldname
	for fn in ("custom_length_mtrs", "length_mtrs", "custom_meter_roll", "meter_roll"):
		if batch_meta.has_field(fn):
			return fn
	return None


def _spr_length_meters(spr_row) -> float | None:
	"""Length in m for Batch + reporting: prefers Produced Length (Mtrs), then Meter/Roll."""
	if spr_row is None:
		return None
	for key in ("produced_length_mtrs", "custom_produced_length_mtrs"):
		v = _spr_row_get(spr_row, key)
		if v is not None and flt(v) > 0:
			return flt(v)
	try:
		spi_meta = frappe.get_meta("Shaft Production Run Item")
		for df in spi_meta.fields:
			if df.fieldtype not in ("Float", "Int", "Currency"):
				continue
			lab = (df.label or "").lower()
			if "produced" in lab and "length" in lab:
				v = _spr_row_get(spr_row, df.fieldname)
				if v is not None and flt(v) > 0:
					return flt(v)
	except Exception:
		pass
	for key in ("meter_roll", "ordered_length", "custom_ordered_length"):
		v = _spr_row_get(spr_row, key)
		if v is not None and flt(v) > 0:
			return flt(v)
	return None


def _batch_fields_from_spr_row(batch_meta, spr_row) -> dict:
	"""Map Roll Production Result line to Batch fields (Net/Gross Weight Kgs, Length Mtrs, CBM)."""
	if not spr_row:
		return {}
	out = {}
	fn_n = _batch_field_net_weight_kgs(batch_meta)
	fn_g = _batch_field_gross_weight_kgs(batch_meta)
	fn_l = _batch_field_length_mtrs(batch_meta)
	if fn_n is not None and _spr_row_get(spr_row, "net_weight") is not None:
		out[fn_n] = flt(_spr_row_get(spr_row, "net_weight"))
	if fn_g is not None and _spr_row_get(spr_row, "gross_weight") is not None:
		out[fn_g] = flt(_spr_row_get(spr_row, "gross_weight"))
	ln = _spr_length_meters(spr_row)
	if fn_l is not None and ln is not None:
		out[fn_l] = flt(ln)
	if batch_meta.has_field("custom_cbm") and _spr_row_get(spr_row, "custom_cbm") is not None:
		out["custom_cbm"] = flt(_spr_row_get(spr_row, "custom_cbm"))
	return out


def _production_plan_custom_shaft_child_doctype() -> str | None:
	"""Child table Doctype behind Production Plan.custom_shaft_details (e.g. Shaft Plan Detail)."""
	try:
		pp_meta = frappe.get_meta("Production Plan")
	except Exception:
		return None
	for fname in ("custom_shaft_details", "custom_shaft_detail"):
		if not pp_meta.has_field(fname):
			continue
		f = pp_meta.get_field(fname)
		if f.fieldtype == "Table" and f.options:
			return f.options
	return None


def _looks_like_frappe_row_name(s: str) -> bool:
	"""Heuristic: autogenerated child row names are often long alphanumeric strings."""
	t = _cstr(s)
	if len(t) < 9:
		return False
	return t.isalnum()


def _production_plan_total_planned_qty(production_plan: str) -> float:
	"""Resolve planned KG from Production Plan fields, then fall back to linked Work Orders sum."""
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return 0.0

	try:
		wo_qty = flt(
			frappe.db.sql(
				"""
				SELECT IFNULL(SUM(wo.qty), 0)
				FROM `tabWork Order` wo
				WHERE wo.production_plan = %(pp)s
				  AND wo.docstatus < 2
				""",
				{"pp": production_plan},
			)[0][0]
		)
		frappe.logger().info(f"[_production_plan_total_planned_qty] {production_plan}: WO qty sum = {wo_qty}")
		if wo_qty > 0:
			return wo_qty
	except Exception as e:
		frappe.logger().error(f"[_production_plan_total_planned_qty] Error fetching WO sum for {production_plan}: {e}")
		pass

	# Final fallback to direct PP fields
	try:
		pp = frappe.get_doc("Production Plan", production_plan)
		pp_meta = frappe.get_meta("Production Plan")
		for fn in ("custom_total_planned_qty", "total_planned_qty", "planned_qty", "qty"):
			if pp_meta.has_field(fn):
				v = flt(pp.get(fn))
				if v > 0:
					return v
	except Exception:
		pass
		
	return 0.0


def _effective_weight_kg_for_produced_gsm(row) -> float:
	"""Prefer net weight; if not entered yet, use gross (same rule as desk JS spr_update_produced_gsm)."""
	nw = flt(getattr(row, "net_weight", None))
	if nw > 0:
		return nw
	return flt(getattr(row, "gross_weight", None))


def compute_produced_gsm(weight_kg, width_inch, length_m) -> float:
	"""Roll line GSM from actuals: (weight_kg * 10000) / (width_inch * length_m * 0.254)."""
	wgt = flt(weight_kg)
	w = flt(width_inch)
	ln = flt(length_m)
	den = w * ln * 0.254
	if den <= 0:
		return 0.0
	return round((wgt * 10000.0) / den, 2)


def _work_order_names_for_pp_job(production_plan: str, m: dict, idx: int) -> str:
	"""Comma-separated WO names for this shaft row (same rules as _get_work_orders_for_spr_job)."""
	
	# Extract GSM if available in job row
	job_gsm = None
	try:
		if m.get("gsm"):
			job_gsm = int(flt(m.get("gsm")))
	except Exception:
		pass

	wos = _resolve_wos_for_pp_job_row(
		production_plan,
		ppi=m.get("production_plan_item"),
		job_id=m.get("job_id"),
		row_index=idx,
		combination=m.get("combination"),
		job_gsm=job_gsm,
	)
	return ", ".join(w["name"] for w in wos) if wos else ""


def _build_shaft_jobs_from_custom_shaft_details(production_plan: str) -> list[dict] | None:
	"""
	Load Available Jobs from Production Plan.custom_shaft_details (Table field on PP).
	Maps rows to Shaft Production Run Job; prefers human-readable Job column for job_id.
	"""
	child_dt = _production_plan_custom_shaft_child_doctype()
	if not child_dt or not frappe.db.exists("DocType", child_dt):
		return None
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return None
	pp_rows = frappe.db.sql(
		f"""
		SELECT * FROM `tab{child_dt}`
		WHERE parent = %(p)s
		ORDER BY idx ASC
		""",
		{"p": production_plan},
		as_dict=True,
	)
	if not pp_rows:
		return None
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out: list[dict] = []
	for idx, r in enumerate(pp_rows):
		m: dict = {}
		# Shaft Plan Detail: Job is field s_no (Int); also accept job / job_no / job_id
		readable = None
		if r.get("s_no") is not None and _cstr(r.get("s_no")) != "":
			try:
				readable = str(int(flt(r["s_no"])))
			except (TypeError, ValueError):
				readable = _cstr(r.get("s_no"))
		if not readable:
			readable = (
				_cstr(r.get("job"))
				if r.get("job") is not None and _cstr(r.get("job")) != ""
				else None
			)
		if not readable:
			readable = r.get("job_no") or r.get("job_id")
		if not readable or _cstr(readable) == "":
			readable = str(idx + 1)
		m["job_id"] = _cstr(readable)

		ppi = r.get("production_plan_item") or r.get("against_production_plan_item")
		if not ppi and _looks_like_frappe_row_name(_cstr(r.get("name", ""))):
			ppi = r.get("name")
		if ppi and job_meta.has_field("production_plan_item"):
			m["production_plan_item"] = _cstr(ppi)

		comb = r.get("shaft_combination") or r.get("combination")
		if comb is not None and job_meta.has_field("combination"):
			m["combination"] = comb

		# Map Shaft Plan Detail fieldnames: combined_width, meter__roll, no_of_shaft, total_weight_kgs
		field_aliases = {
			"gsm": ("gsm", "custom_gsm"),
			"quality": ("quality", "custom_quality"),
			"notes": ("notes", "custom_notes"),
			"total_width": (
				"combined_width",
				"total_width",
				"total_width_inches",
				"custom_total_width",
			),
			"meter_roll_mtrs": (
				"meter__roll",
				"meter_roll_mtrs",
				"meter_per_roll",
				"custom_meter_roll_mtrs",
			),
			"no_of_shafts": ("no_of_shafts", "no_of_shaft", "custom_no_of_shafts"),
			"net_weight": ("net_weight", "net_weight_per_shaft", "custom_net_weight_per_shaft"),
			"total_weight": ("total_weight_kgs", "total_weight", "custom_total_weight"),
			"custom_total_achieved_weight": ("custom_total_achieved_weight",),
			"party_code": ("party_code", "order_code", "custom_party_code"),
			"work_orders": ("work_orders", "custom_work_orders"),
		}
		for target, aliases in field_aliases.items():
			if not job_meta.has_field(target):
				continue
			for a in aliases:
				if a in r and r[a] is not None and _cstr(r[a]) != "":
					val = r[a]
					if target == "net_weight" and not isinstance(val, str):
						val = str(val)
					m[target] = val
					break

		if m.get("gsm") is not None and m.get("gsm") != "":
			try:
				m["gsm"] = int(flt(str(m["gsm"]).strip().split()[0]))
			except Exception:
				pass

		skip_copy = {
			"name",
			"owner",
			"creation",
			"modified",
			"modified_by",
			"docstatus",
			"idx",
			"parent",
			"parentfield",
			"parenttype",
			"doctype",
		}
		skip_alias = {
			"job",
			"job_no",
			"job_id",
			"s_no",
			"name",
			"production_plan_item",
			"against_production_plan_item",
			"shaft_combination",
			"combination",
			"combined_width",
			"meter__roll",
			"no_of_shaft",
			"total_weight_kgs",
		}
		for fn, v in r.items():
			if fn in skip_copy or fn in skip_alias or v is None:
				continue
			if not job_meta.has_field(fn):
				continue
			if fn not in m:
				if fn == "net_weight" and not isinstance(v, str):
					m[fn] = str(v)
				else:
					m[fn] = v

		jn = m.get("job_id")
		if jn and (not m.get("total_weight")):
			wos_tw = _resolve_wos_for_pp_job_row(
				production_plan,
				ppi=m.get("production_plan_item"),
				job_id=_cstr(jn),
				row_index=idx,
				combination=m.get("combination"),
			)
			tw = sum(flt(w.get("planned_qty")) for w in wos_tw) if wos_tw else 0.0
			if flt(tw) > 0:
				m["total_weight"] = flt(tw)

		if job_meta.has_field("work_orders"):
			m["work_orders"] = _work_order_names_for_pp_job(production_plan, m, idx)

		out.append(m)
	return out or None


def _ordered_production_plan_items(production_plan: str) -> list[str]:
	"""Distinct Work Order production_plan_item values in stable order (for ordinal WO fallback)."""
	rows = frappe.db.sql(
		"""
		SELECT wo.production_plan_item AS ppi, MIN(wo.creation) AS mc
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		  AND IFNULL(wo.production_plan_item, '') != ''
		GROUP BY wo.production_plan_item
		ORDER BY mc ASC, ppi ASC
		""",
		{"pp": production_plan},
		as_dict=True,
	)
	return [_cstr(r.ppi) for r in rows]


def _spr_job_row_index(spr_doc, job_row) -> int | None:
	rows = list(_spr_job_rows(spr_doc))
	for i, r in enumerate(rows):
		if getattr(r, "name", None) and getattr(job_row, "name", None) and r.name == job_row.name:
			return i
	jid = _cstr(_spr_job_id(job_row))
	for i, r in enumerate(rows):
		if _cstr(_spr_job_id(r)) == jid:
			return i
	return None


def _get_all_work_orders_for_production_plan(pp_name: str) -> list:
	"""All Work Orders for a Production Plan (fallback when job id does not match production_plan_item)."""
	if not pp_name:
		return []
	return frappe.db.sql(
		"""
		SELECT wo.name, wo.production_item, wo.qty as planned_qty, wo.produced_qty, wo.status
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus != 2
		ORDER BY wo.creation ASC, wo.name ASC
		""",
		{"pp": pp_name},
		as_dict=True,
	)


def _parse_combination_widths_inches(combination) -> list[float]:
	"""Numeric widths per '+' segment, aligned with _count_combination_segments (e.g. 39\" + 24\" → [39, 24])."""
	if not combination:
		return []
	parts = [p.strip() for p in re.split(r"\+", str(combination)) if p.strip()]
	out: list[float] = []
	for part in parts:
		m = re.search(r"(\d+(?:\.\d+)?)", part.replace(",", ""))
		if m:
			out.append(flt(m.group(1)))
	return out


def _match_work_orders_to_combination_segments(pp_name: str, combination: str, ppi: str | None = None, job_gsm: int | None = None) -> list | None:
	"""
	For multi-width combinations (e.g. "33+63" or "63+63"),
	match WO by BOTH GSM AND WIDTH (not just width).
	
	⚠️ CRITICAL: Get WOs ONLY for the specific PPI, not all WOs in PP!
	This ensures "25 GSM 63+63" uses only the WO(s) linked to that PPI.
	"""
	comb = _cstr(combination)
	if not comb:
		return None
	segs = _count_combination_segments(comb)
	if segs < 2:
		return None
	widths = _parse_combination_widths_inches(comb)
	if len(widths) < segs:
		return None
	widths = widths[:segs]
	
	# ✅ CRITICAL: Get WOs ONLY for this PPI, not all in PP!
	if ppi:
		all_wos = get_work_orders_for_job(pp_name, _cstr(ppi))
	else:
		all_wos = _get_all_work_orders_for_production_plan(pp_name)
	
	if not all_wos:
		return None
	
	# ✅ Build (GSM, WIDTH) → WO map using ITEM CODE parsing
	gsm_width_to_wo_map = {}
	for wo in all_wos:
		wo_name = _cstr(wo.get("name"))
		try:
			production_item = wo.get("production_item")
			if not production_item:
				continue
			# Parse item code to extract GSM and WIDTH
			parsed_gsm, parsed_width = parse_item_code(_cstr(production_item))
			if parsed_gsm > 0 and parsed_width > 0:
				key = (parsed_gsm, parsed_width)
				gsm_width_to_wo_map[key] = wo
				frappe.logger().info(f"[COMBO] WO {wo_name} = ({parsed_gsm}, {parsed_width}\") (PPI {ppi})")
		except Exception as e:
			frappe.logger().warning(f"[COMBO ERROR] Could not parse WO {wo_name}: {str(e)}")
	
	if not job_gsm:
		frappe.logger().warning(f"[COMBO] No job_gsm provided, cannot match")
		return None
	
	out: list = []
	tol = 1.25
	for target_w in widths:
		# Match by (GSM, WIDTH) tuple
		key = (job_gsm, target_w)
		if key in gsm_width_to_wo_map:
			best = gsm_width_to_wo_map[key]
			out.append(best)
			frappe.logger().info(f"[COMBO] Segment ({job_gsm}, {target_w}\") → WO {best.get('name')}")
		else:
			# Fallback: find by width closest to target
			best = None
			best_d = 999.0
			for (w_gsm, w_width), wo in gsm_width_to_wo_map.items():
				if abs(w_width - target_w) < best_d:
					best_d = abs(w_width - target_w)
					best = wo
			
			if best and best_d <= tol:
				out.append(best)
				frappe.logger().warning(f"[COMBO] No exact match for ({job_gsm}, {target_w}\"), fallback")
			else:
				frappe.logger().warning(f"[COMBO] No WO found for ({job_gsm}, {target_w}\")")
				return None
	
	# ✅ DEDUPLICATE: For "63+63", return only UNIQUE WOs
	seen = set()
	unique_out = []
	for wo in out:
		wo_name = _cstr(wo.get("name"))
		if wo_name not in seen:
			seen.add(wo_name)
			unique_out.append(wo)
			frappe.logger().info(f"[COMBO DEDUP] Keep WO {wo_name}")
		else:
			frappe.logger().info(f"[COMBO DEDUP] Skip duplicate WO {wo_name}")
	
	return unique_out if len(unique_out) > 0 else None


def _wo_has_gsm(wo: dict, target_gsm: int) -> bool:
	"""Check if a WO's item has matching GSM."""
	try:
		prod_item = wo.get("production_item")
		if prod_item:
			gsm, width = parse_item_code(_cstr(prod_item))
			return gsm == target_gsm
	except Exception:
		pass
	return False


def _resolve_wos_for_pp_job_row(
	pp_name: str,
	*,
	ppi: str | None = None,
	job_id: str | None = None,
	row_index: int | None = None,
	combination: str | None = None,
	job_gsm: int | None = None,
) -> list:
	"""Return exactly one WO per Available Jobs row: PPI → optional GSM match → safe fallbacks.

	``combination`` is accepted for API compatibility (e.g. 63\"+63\") but we do **not** allocate
	one WO per segment here — same-width combo lines share one WO. Multi-GSM combos are handled by
	filtering WOs on the job row GSM when multiple WOs exist for the same PPI.
	"""
	if ppi:
		wos = get_work_orders_for_job(pp_name, _cstr(ppi))
		if not wos:
			return []
		if len(wos) == 1:
			return wos
		if job_gsm and job_gsm > 0:
			for wo in wos:
				try:
					prod_item = wo.get("production_item")
					if prod_item:
						gsm, _width = parse_item_code(_cstr(prod_item))
						if gsm == job_gsm:
							return [wo]
				except Exception:
					pass
		return [wos[0]]

	if job_id:
		wos = get_work_orders_for_job(pp_name, _cstr(job_id))
		return [wos[0]] if wos else []

	if row_index is not None:
		ord_ppi = _ordered_production_plan_items(pp_name)
		if ord_ppi and 0 <= row_index < len(ord_ppi):
			wos = get_work_orders_for_job(pp_name, ord_ppi[row_index])
			return [wos[0]] if wos else []

	all_wos = _get_all_work_orders_for_production_plan(pp_name)
	return [all_wos[0]] if all_wos else []


def _get_work_orders_for_spr_job(pp_name: str, spr_doc, job_row):
	"""Resolve Work Orders using production_plan_item, job_id, or ordinal row index."""
	meta = frappe.get_meta("Shaft Production Run Job")
	ppi = None
	if meta.has_field("production_plan_item"):
		ppi = getattr(job_row, "production_plan_item", None)
	jid = _spr_job_id(job_row)
	idx = _spr_job_row_index(spr_doc, job_row)
	comb = getattr(job_row, "combination", None) if meta.has_field("combination") else None
	# ✅ Extract GSM from job_row for (GSM, WIDTH) matching
	job_gsm = None
	if meta.has_field("gsm"):
		try:
			gsm_val = getattr(job_row, "gsm", None)
			if gsm_val:
				job_gsm = int(flt(gsm_val))
		except Exception:
			pass
	return _resolve_wos_for_pp_job_row(pp_name, ppi=ppi, job_id=jid, row_index=idx, combination=comb, job_gsm=job_gsm)


def _build_shaft_jobs_from_pp_details(production_plan: str) -> list[dict] | None:
	"""One row per Production Plan Shaft Detail line, field-aligned with Shaft Production Run Job."""
	if not production_plan or not frappe.db.exists("DocType", "Production Plan Shaft Detail"):
		return None
	if not frappe.db.exists("Production Plan", production_plan):
		return None
	pp_rows = frappe.db.sql(
		"""
		SELECT * FROM `tabProduction Plan Shaft Detail`
		WHERE parent = %(p)s
		ORDER BY idx ASC
		""",
		{"p": production_plan},
		as_dict=True,
	)
	if not pp_rows:
		return None
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out: list[dict] = []
	for idx, r in enumerate(pp_rows):
		m: dict = {}
		jn = r.get("job_no") or r.get("job_id")
		if not jn:
			continue
		m["job_id"] = _cstr(jn)
		if job_meta.has_field("production_plan_item"):
			m["production_plan_item"] = _cstr(jn)
		if r.get("shaft_combination") is not None and job_meta.has_field("combination"):
			m["combination"] = r.get("shaft_combination")
		for fn in (
			"gsm",
			"quality",
			"combination",
			"notes",
			"total_width",
			"meter_roll_mtrs",
			"net_weight",
			"total_weight",
			"custom_total_achieved_weight",
			"no_of_shafts",
			"party_code",
			"work_orders",
		):
			if fn in r and r[fn] is not None and job_meta.has_field(fn):
				m[fn] = r[fn]
		if (not m.get("total_weight")) and jn:
			job_gsm = None
			if m.get("gsm"):
				try:
					job_gsm = int(flt(m.get("gsm")))
				except Exception:
					pass
			wos_tw = _resolve_wos_for_pp_job_row(
				production_plan,
				ppi=m.get("production_plan_item"),
				job_id=_cstr(jn),
				row_index=idx,
				combination=m.get("combination"),
				job_gsm=job_gsm,
			)
			tw = sum(flt(w.get("planned_qty")) for w in wos_tw) if wos_tw else 0.0
			if flt(tw) > 0:
				m["total_weight"] = flt(tw)
		if job_meta.has_field("work_orders") and not m.get("work_orders"):
			m["work_orders"] = _work_order_names_for_pp_job(production_plan, m, idx)
		out.append(m)
	return out or None


class ShaftProductionRun(Document):
	def validate(self):
		self.sync_shaft_job_work_orders_from_plan()
		self.calculate_produced_gsm()
		self.recalculate_job_achieved_weights()
		self.generate_batch_numbers()

	def sync_shaft_job_work_orders_from_plan(self):
		"""Fill Available Jobs.work_orders from Production Plan (one WO per row; GSM disambiguates when several WOs share a PPI)."""
		meta = frappe.get_meta("Shaft Production Run Job")
		if not meta.has_field("work_orders"):
			return
		pp = self.get("production_plan")
		if not pp:
			return
		for row in self.shaft_jobs or []:
			if cint(getattr(row, "is_manual", 0)):
				continue
			idx = _spr_job_row_index(self, row)
			if idx is None:
				idx = 0
			# ✅ Extract GSM from row for (GSM, WIDTH) matching
			job_gsm = None
			if meta.has_field("gsm"):
				try:
					gsm_val = getattr(row, "gsm", None)
					if gsm_val:
						job_gsm = int(flt(gsm_val))
				except Exception:
					pass
			m = {
				"job_id": _spr_job_id(row),
				"production_plan_item": getattr(row, "production_plan_item", None),
				"combination": getattr(row, "combination", None),
			}
			wos = _resolve_wos_for_pp_job_row(
				pp,
				ppi=m.get("production_plan_item"),
				job_id=_cstr(m.get("job_id")),
				row_index=idx,
				combination=m.get("combination"),
				job_gsm=job_gsm,
			)
			if wos:
				row.work_orders = ", ".join(w["name"] for w in wos)

	def sync_roll_line_net_weights_from_planned(self):
		"""No longer used on save: net weight must come from operators or site scripts, not planned qty."""
		pass

	def recalculate_job_achieved_weights(self):
		"""Total Achieved Weight on each Available Jobs row = sum of net_weight in Roll Results for that job."""
		meta = frappe.get_meta("Shaft Production Run Job")
		if not meta.has_field("custom_total_achieved_weight"):
			return
		sums: dict[str, float] = {}
		for it in self.items or []:
			jid = _cstr(getattr(it, "job", None))
			if not jid:
				continue
			sums[jid] = sums.get(jid, 0.0) + flt(it.net_weight)
		for row in self.shaft_jobs or []:
			jid = _cstr(_spr_job_id(row))
			row.custom_total_achieved_weight = flt(sums.get(jid, 0.0))

	def calculate_produced_gsm(self):
		"""Set produced_gsm on each roll line from effective weight (net, else gross), width, length (m)."""
		meta = frappe.get_meta("Shaft Production Run Item")
		if not meta.has_field("produced_gsm"):
			return
		for row in self.items or []:
			ln = _spr_length_meters(row)
			if ln is None or ln <= 0:
				ln = flt(getattr(row, "meter_roll", None))
			else:
				ln = flt(ln)
			wgt = _effective_weight_kg_for_produced_gsm(row)
			row.produced_gsm = compute_produced_gsm(wgt, row.width_inch, ln)

	def on_submit(self):
		self.sync_batch_custom_fields()
		self.create_manufacturing_stock_entries()
		self.update_work_order_statuses()

	def on_cancel(self):
		self.cancel_manufacturing_stock_entries()

	def on_trash(self):
		"""Remove stale row links so deleted SPR is not shown as Continue Entry on Production Table."""
		try:
			if frappe.db.exists("DocType", "Planning Table") and frappe.db.has_column("Planning Table", "spr_name"):
				frappe.db.sql(
					"""
					UPDATE `tabPlanning Table`
					SET spr_name = ''
					WHERE IFNULL(spr_name, '') = %s
					""",
					(self.name,),
				)
		except Exception:
			frappe.log_error(frappe.get_traceback(), "SPR on_trash cleanup: Planning Table spr_name")

		# Also remove this SPR from Production Plan link list to avoid stale PP-level references elsewhere.
		try:
			if not frappe.db.has_column("Production Plan", "custom_shaft_production_run_id"):
				return
			rows = frappe.db.sql(
				"""
				SELECT name, custom_shaft_production_run_id
				FROM `tabProduction Plan`
				WHERE IFNULL(custom_shaft_production_run_id, '') != ''
				""",
				as_dict=True,
			)
			for r in rows or []:
				raw = str(r.get("custom_shaft_production_run_id") or "")
				parts = [p.strip() for p in raw.split(",") if p and p.strip()]
				filtered = [p for p in parts if p != self.name]
				if filtered != parts:
					frappe.db.set_value("Production Plan", r["name"], "custom_shaft_production_run_id", ", ".join(filtered))
		except Exception:
			frappe.log_error(frappe.get_traceback(), "SPR on_trash cleanup: Production Plan links")

	def _unit_digit(self) -> int:
		u = (self.get("custom_unit") or "").strip()
		if not u:
			return 0
		m = re.search(r"(\d+)", u)
		return int(m.group(1)) if m else 0

	def generate_batch_numbers(self):
		"""Assign batch_no on each roll line when draft is saved (after Create Entry + required header fields).

		Format: ``{MM}{U}{YY}{S}/{N}`` — month (2) + unit digit + year (2) + shift suffix ``S`` + ``/`` + roll sequence ``N``.
		``tabBatch`` rows are created/updated on **submit** via ``sync_batch_custom_fields``, not on every save.
		"""
		if not self.run_date or not self.get("custom_unit") or not self.shift:
			return
		rows = [r for r in (self.items or []) if r.item_code]
		if not rows:
			return
		rd = getdate(self.run_date)
		unit_d = self._unit_digit()
		root_5 = f"{rd.month:02d}{unit_d}{rd.year % 100:02d}"
		series_prefix = self._resolve_series_prefix(root_5)
		next_roll = self._next_roll_starting(series_prefix)
		item_meta = frappe.get_meta("Shaft Production Run Item")
		for row in rows:
			if row.batch_no:
				continue
			row.batch_no = f"{series_prefix}/{next_roll}"
			if item_meta.has_field("roll_no"):
				rf = item_meta.get_field("roll_no")
				row.roll_no = int(next_roll) if rf and rf.fieldtype == "Int" else str(next_roll)
			if item_meta.has_field("custom_shift"):
				row.custom_shift = batch_shift_value(self.shift)
			next_roll += 1

	def _resolve_series_prefix(self, root_5: str) -> str:
		"""Reuse series for same run_date + shift + unit when batches already exist."""
		existing = frappe.db.sql(
			"""
			SELECT spi.batch_no
			FROM `tabShaft Production Run Item` spi
			INNER JOIN `tabShaft Production Run` spr ON spr.name = spi.parent
			WHERE spr.run_date = %(rd)s
			  AND spr.shift = %(sh)s
			  AND spr.custom_unit = %(un)s
			  AND spr.name != %(cur)s
			  AND IFNULL(spi.batch_no, '') != ''
			  AND spi.batch_no LIKE CONCAT(%(root)s, '%%')
			ORDER BY spr.modified DESC
			LIMIT 20
			""",
			{
				"rd": self.run_date,
				"sh": self.shift,
				"un": self.custom_unit,
				"cur": self.name or "",
				"root": root_5,
			},
		)
		for (bn,) in existing or []:
			if bn and "/" in bn:
				pref = bn.split("/")[0].strip()
				if pref.startswith(root_5) and len(pref) >= 6:
					return pref

		next_s = self._next_shift_suffix_num(root_5)
		return f"{root_5}{next_s}"

	def _next_shift_suffix_num(self, root_5: str) -> int:
		"""Pick next S digit(s) after scanning Batch + SPR items for this month/unit/year root."""
		max_s = 0
		rows = frappe.db.sql(
			"""
			SELECT batch_id FROM `tabBatch`
			WHERE batch_id LIKE CONCAT(%(root)s, '%%')
			""",
			{"root": root_5},
		)
		for (bid,) in rows or []:
			max_s = max(max_s, self._suffix_after_root(bid, root_5))
		rows2 = frappe.db.sql(
			"""
			SELECT spi.batch_no FROM `tabShaft Production Run Item` spi
			WHERE IFNULL(spi.batch_no,'') != ''
			  AND spi.batch_no LIKE CONCAT(%(root)s, '%%')
			""",
			{"root": root_5},
		)
		for (bn,) in rows2 or []:
			max_s = max(max_s, self._suffix_after_root(bn, root_5))
		return max_s + 1 if max_s >= 0 else 1

	def _suffix_after_root(self, batch_id: str, root_5: str) -> int:
		if not batch_id or "/" not in batch_id:
			return 0
		pref = batch_id.split("/", 1)[0].strip()
		if not pref.startswith(root_5):
			return 0
		s_part = pref[len(root_5) :]
		try:
			return int(s_part) if s_part else 0
		except ValueError:
			return 0

	def _next_roll_starting(self, series_prefix: str) -> int:
		mx = 0
		rows = frappe.db.sql(
			"""
			SELECT batch_id FROM `tabBatch`
			WHERE batch_id LIKE %(pat)s
			""",
			{"pat": f"{series_prefix}/%"},
		)
		for (bid,) in rows or []:
			mx = max(mx, self._roll_no_from_batch(bid, series_prefix))
		rows2 = frappe.db.sql(
			"""
			SELECT batch_no FROM `tabShaft Production Run Item`
			WHERE IFNULL(batch_no,'') != '' AND batch_no LIKE %(pat)s
			""",
			{"pat": f"{series_prefix}/%"},
		)
		for (bn,) in rows2 or []:
			mx = max(mx, self._roll_no_from_batch(bn, series_prefix))
		return mx + 1

	def _roll_no_from_batch(self, batch_id: str, series_prefix: str) -> int:
		if not batch_id or "/" not in batch_id:
			return 0
		pref, roll = batch_id.split("/", 1)
		if pref.strip() != series_prefix:
			return 0
		try:
			return int(roll.strip())
		except ValueError:
			return 0

	def sync_batch_custom_fields(self):
		batch_meta = frappe.get_meta("Batch")
		for row in self.items or []:
			if not row.batch_no:
				continue
			bn = _cstr(row.batch_no)
			batch_name = bn
			if not frappe.db.exists("Batch", batch_name) and row.get("item_code"):
				batch_name = (
					frappe.db.get_value(
						"Batch",
						{"item": row.item_code, "batch_id": bn},
						"name",
					)
					or batch_name
				)
			if not batch_name or not frappe.db.exists("Batch", batch_name):
				continue
			data = dict(_batch_fields_from_spr_row(batch_meta, row))
			if batch_meta.has_field("custom_gross_weight") and row.get("gross_weight") is not None:
				data["custom_gross_weight"] = flt(row.gross_weight)
			if batch_meta.has_field("custom_cbm") and row.get("custom_cbm") is not None:
				data["custom_cbm"] = flt(row.custom_cbm)
			if batch_meta.has_field("custom_diameter") and row.get("custom_diameter") is not None:
				data["custom_diameter"] = flt(row.custom_diameter)
			if batch_meta.has_field("custom_shift") and row.get("custom_shift"):
				data["custom_shift"] = row.custom_shift
			if batch_meta.has_field("custom_party_code_text") and row.get("custom_party_code_text"):
				data["custom_party_code_text"] = row.custom_party_code_text
			if not data:
				continue
			try:
				frappe.db.set_value("Batch", batch_name, data)
			except Exception:
				frappe.log_error(frappe.get_traceback(), "SPR Batch sync skipped")

	def _row_fg_qty(self, row) -> float:
		qty = flt(row.net_weight)
		if qty <= 0:
			qty = flt(row.gross_weight)
		return qty

	def _set_stock_entry_spr_link(self, se):
		meta = frappe.get_meta("Stock Entry")
		if meta.has_field("shaft_production_run"):
			se.shaft_production_run = self.name

	def _strip_finished_goods_from_stock_entry(self, se):
		"""Remove FG rows from BOM-generated Stock Entry (we re-add per roll with batch_no)."""
		items = se.get("items") or []
		for i in range(len(items) - 1, -1, -1):
			if getattr(items[i], "is_finished_item", 0):
				se.items.pop(i)

	def _get_batch_link_name_for_stock_entry(
		self,
		batch_id: str,
		item_code: str,
		company: str | None,
		spr_row=None,
	) -> str:
		"""
		Return tabBatch.name for Stock Entry Detail `batch_no` (Link).
		Frappe's savedocs validates every Link: the value must exist as Batch.name before insert().
		ERPNext Batch.autoname sets name = batch_id when batch_id is provided; use ERPNext make_batch when available.
		``spr_row`` fills Batch mandatory custom fields (net/gross weight, length) from the roll line.
		"""
		bid = _cstr(batch_id)
		if not bid:
			return ""

		batch_meta = frappe.get_meta("Batch")
		roll_batch_data = _batch_fields_from_spr_row(batch_meta, spr_row)

		def _existing_name() -> str | None:
			if frappe.db.exists("Batch", bid):
				it = frappe.db.get_value("Batch", bid, "item")
				if it == item_code:
					return bid
			nm = frappe.db.get_value(
				"Batch",
				{"item": item_code, "batch_id": bid},
				"name",
			)
			if nm:
				return nm
			return frappe.db.get_value("Batch", {"batch_id": bid, "item": item_code}, "name")

		found = _existing_name()
		if found:
			if roll_batch_data:
				try:
					frappe.db.set_value("Batch", found, roll_batch_data)
				except Exception:
					frappe.log_error(frappe.get_traceback(), "SPR Batch roll fields on existing Batch")
			return found

		try:
			from erpnext.stock.doctype.batch.batch import make_batch

			kw = frappe._dict(
				item=item_code,
				batch_id=bid,
				manufacturing_date=self.run_date or today(),
			)
			if company:
				if batch_meta.has_field("company"):
					kw.company = company
			for fk, fv in roll_batch_data.items():
				kw[fk] = fv
			mb = make_batch(kw)
			if mb:
				return mb
		except ImportError:
			pass
		except Exception:
			found = _existing_name()
			if found:
				return found

		b = frappe.new_doc("Batch")
		b.batch_id = bid
		b.item = item_code
		if batch_meta.has_field("company") and company:
			b.company = company
		if batch_meta.has_field("manufacturing_date"):
			b.manufacturing_date = self.run_date or today()
		for fk, fv in roll_batch_data.items():
			b.set(fk, fv)
		try:
			b.insert(ignore_permissions=True)
			return b.name
		except Exception:
			found = _existing_name()
			if found:
				return found
			raise

	def _append_manufacture_fg_from_spr_rolls(self, se, wo_doc, spr_rows: list):
		"""One finished-good Stock Entry line per SPR roll (no merging qty by batch)."""
		item_code = wo_doc.production_item
		has_batch = cint(frappe.db.get_value("Item", item_code, "has_batch_no"))
		stock_uom = frappe.db.get_value("Item", item_code, "stock_uom") or "Kg"
		item_name = frappe.db.get_value("Item", item_code, "item_name")

		for spr in spr_rows:
			qty = self._row_fg_qty(spr)
			if qty <= 0:
				continue
			bn_raw = spr.get("batch_no")
			bn = _cstr(bn_raw) if bn_raw is not None else ""
			if has_batch:
				if not bn:
					frappe.throw(
						_("Batch No is required on each roll line for batch-tracked item {0}").format(
							item_code
						),
						title=_("Missing Batch"),
					)
				se_batch = self._get_batch_link_name_for_stock_entry(
					bn, item_code, wo_doc.company, spr
				)
				if not se_batch:
					frappe.throw(
						_("Could not resolve Batch master for batch id {0}").format(bn),
						title=_("Batch"),
					)
			else:
				se_batch = ""

			row = {
				"item_code": item_code,
				"item_name": item_name,
				"qty": qty,
				"uom": stock_uom,
				"t_warehouse": wo_doc.fg_warehouse,
				"is_finished_item": 1,
			}
			if has_batch and se_batch:
				row["batch_no"] = se_batch
			se.append("items", row)

	def create_manufacturing_stock_entries(self):
		"""One Stock Entry (Manufacture) per Work Order, same pattern as Roll Production Entry."""
		wo_groups = {}
		for row in self.items or []:
			wo_name = row.get("work_order") or row.get("wo_id")
			if not wo_name:
				continue
			wo_groups.setdefault(wo_name, []).append(row)

		created_entries = []

		for wo_id, rows in wo_groups.items():
			wo_doc = frappe.get_doc("Work Order", wo_id)
			total_qty = sum(self._row_fg_qty(r) for r in rows)
			
			# 📊 DEBUG: Log WO and total quantity
			frappe.logger().info(f"[SPR CREATE] Processing WO: {wo_id}, SPR Total Qty: {total_qty} KG, WO Authorized Qty: {wo_doc.qty} KG")
			
			# Show in UI
			frappe.msgprint(
				_(f"📊 Creating Manufacturing Entry for WO: {wo_id} | Total Quantity: {total_qty} KG | WO Authorized: {wo_doc.qty} KG"),
				alert=False
			)

			if total_qty <= 0:
				frappe.msgprint(_("Skipping WO {0} — net/gross weight is 0").format(wo_id), alert=True)
				continue

			# 🔒 VALIDATION: Ensure WIP warehouse exists
			if not wo_doc.wip_warehouse:
				frappe.throw(
					_("Work Order {0} has no WIP warehouse set. Raw materials cannot be fetched.").format(wo_id),
					title=_("Missing WIP Warehouse")
				)

			se = frappe.new_doc("Stock Entry")
			se.company = wo_doc.company
			se.posting_date = self.run_date or today()
			se.posting_time = nowtime()
			se.set_posting_time = 1
			se.stock_entry_type = "Manufacture"
			# ERPNext get_items() runs before validate; purpose must be set here or BOM + FG lines are never built.
			se.purpose = "Manufacture"
			se.work_order = wo_id
			se.production_item = wo_doc.production_item
			se.fg_completed_qty = total_qty
			se.from_bom = 1
			se.bom_no = wo_doc.bom_no
			se.use_multi_level_bom = wo_doc.use_multi_level_bom
			se.wip_warehouse = wo_doc.wip_warehouse
			se.to_warehouse = wo_doc.fg_warehouse

			self._set_stock_entry_spr_link(se)

			# get_items() clears `items` and rebuilds from BOM + finished good; do not append rows before it.
			se.get_items()
			
			# 🔒 ENFORCE: ALL RM items MUST use WIP warehouse ONLY - NO OTHER WAREHOUSE
			# This prevents double consumption (materials already transferred to WIP)
			wip_warehouse = wo_doc.wip_warehouse
			rm_count = 0
			
			for item in se.items or []:
				if item.item_code:
					# Check if this is a RM item (no t_warehouse means it's a raw material)
					if not item.get("t_warehouse"):
						rm_count += 1
						# 🔒 ENFORCE: Set source warehouse to WIP ONLY
						item.s_warehouse = wip_warehouse
						
						# 🔒 VALIDATE: Ensure warehouse was set correctly
						if item.s_warehouse != wip_warehouse:
							frappe.throw(
								_("Raw material {0} source warehouse is {1}, not {2}. ABORT.").format(
									item.item_code, item.s_warehouse, wip_warehouse
								),
								title=_("Warehouse Mismatch")
							)
					else:
						# This is a finished good item - target warehouse should be FG warehouse
						if item.t_warehouse != wo_doc.fg_warehouse:
							item.t_warehouse = wo_doc.fg_warehouse
			
			# Log for verification
			if rm_count > 0:
				frappe.msgprint(
					_("Confirmed: {0} RM items set to use WIP warehouse: {1}").format(rm_count, wip_warehouse),
					alert=False
				)
			
			# Default FG line has no batch; batch-mandatory items require batch_no per ERPNext validation.
			self._strip_finished_goods_from_stock_entry(se)
			self._append_manufacture_fg_from_spr_rolls(se, wo_doc, rows)

			se.insert()
			se.submit()
			created_entries.append(se.name)

			frappe.msgprint(
				_("Manufacturing Entry {0} created for WO {1}").format(se.name, wo_id),
				alert=True,
			)

		if created_entries:
			self.db_set("manufacturing_entries", ", ".join(created_entries))
			frappe.msgprint(
				_("Created {0} Manufacturing Entries: {1}").format(
					len(created_entries), ", ".join(created_entries)
				)
			)

	def update_work_order_statuses(self):
		wo_ids = list(
			{
				(row.get("work_order") or row.get("wo_id"))
				for row in (self.items or [])
				if row.get("work_order") or row.get("wo_id")
			}
		)
		for wo_id in wo_ids:
			wo_doc = frappe.get_doc("Work Order", wo_id)
			total_produced = frappe.db.sql(
				"""
				SELECT IFNULL(SUM(fg_completed_qty), 0)
				FROM `tabStock Entry`
				WHERE work_order = %s
				  AND IFNULL(purpose, '') = 'Manufacture'
				  AND docstatus = 1
				""",
				wo_id,
			)[0][0]

			if flt(total_produced) >= flt(wo_doc.qty):
				wo_doc.db_set("status", "Completed")
				frappe.msgprint(_("Work Order {0} marked as Completed").format(wo_id), alert=True)

	def cancel_manufacturing_stock_entries(self):
		names = []
		if self.manufacturing_entries:
			names = [x.strip() for x in self.manufacturing_entries.split(",") if x.strip()]
		meta_se = frappe.get_meta("Stock Entry")
		if not names and meta_se.has_field("shaft_production_run"):
			conds = [
				"shaft_production_run = %s",
				"IFNULL(purpose, '') = 'Manufacture'",
				"docstatus = 1",
			]
			params = [self.name]
			if meta_se.has_field("roll_production_entry"):
				conds.append("IFNULL(roll_production_entry, '') = ''")
			names = frappe.db.sql_list(
				f"SELECT name FROM `tabStock Entry` WHERE {' AND '.join(conds)}",
				params,
			)
		for name in names:
			if not frappe.db.exists("Stock Entry", name):
				continue
			if frappe.db.get_value("Stock Entry", name, "docstatus") != 1:
				continue
			se = frappe.get_doc("Stock Entry", name)
			se.cancel()
			frappe.msgprint(_("Cancelled Manufacturing Entry {0}").format(name), alert=True)
		self.db_set("manufacturing_entries", "")


@frappe.whitelist()
def get_production_plan_details(production_plan):
	"""Fill header fields from Production Plan."""
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return {}
	pp = frappe.get_doc("Production Plan", production_plan)
	pp_meta = frappe.get_meta("Production Plan")
	out = {
		"customer": pp.get("customer"),
		"custom_unit": pp.get("custom_unit"),
	}
	# custom_order_code comes from PP's custom_party_code
	if pp_meta.has_field("custom_party_code"):
		out["custom_order_code"] = pp.get("custom_party_code") or ""
	
	# Try both custom_label and label fields
	label_value = ""
	if pp_meta.has_field("custom_label"):
		label_value = pp.get("custom_label") or ""
	if not label_value and pp_meta.has_field("label"):
		label_value = pp.get("label") or ""
	if label_value:
		out["custom_label"] = label_value
	
	# Calculate custom_total_planned_qty from WO sum
	out["custom_total_planned_qty"] = _production_plan_total_planned_qty(production_plan)
	
	frappe.logger().info(f"[get_production_plan_details] PP {production_plan}: custom_order_code={out.get('custom_order_code')}, custom_label={out.get('custom_label')}, custom_total_planned_qty={out.get('custom_total_planned_qty')}")
	if pp.get("sales_order"):
		so = frappe.db.get_value(
			"Sales Order", pp.sales_order, ["customer", "transaction_date"], as_dict=True
		)
		if so:
			out["customer"] = out["customer"] or so.customer
	return out


@frappe.whitelist()
def get_production_plan_wo_summary(production_plan):
	"""Work Orders linked to this PP: status, order qty, pending qty — for desk popup after PP is set."""
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return []
	return frappe.db.sql(
		"""
		SELECT
			wo.name AS work_order,
			wo.status,
			IFNULL(wo.qty, 0) AS order_qty,
			GREATEST(0, IFNULL(wo.qty, 0) - IFNULL(wo.produced_qty, 0)) AS pending_qty
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		ORDER BY wo.name
		""",
		{"pp": production_plan},
		as_dict=True,
	)


def _count_combination_segments(combination) -> int:
	"""How many width slots in a combination string like '48\\" + 37\\" + ...'."""
	if not combination:
		return 1
	parts = [p.strip() for p in re.split(r"\+", str(combination)) if p.strip()]
	return max(1, len(parts))


def _parse_net_weight_kg_parts(net_weight) -> list[float]:
	"""Parse '89.61 + 6.2' style net weight from shaft job into kg numbers."""
	if not net_weight:
		return []
	s = str(net_weight).strip()
	if not s:
		return []
	out: list[float] = []
	for part in re.split(r"\s*\+\s*", s):
		part = part.strip()
		if not part:
			continue
		m = re.search(r"(\d+(?:\.\d+)?)", part.replace(",", ""))
		if m:
			out.append(flt(m.group(1)))
	return out


def _segment_weights_kg(job_row, segs: int) -> list[float]:
	"""Per-combination-segment kg; falls back to equal split of total target weight."""
	if segs < 1:
		segs = 1
	parts = _parse_net_weight_kg_parts(getattr(job_row, "net_weight", None))
	tw = flt(getattr(job_row, "total_weight", 0) or 0)
	if len(parts) >= segs:
		return [flt(x) for x in parts[:segs]]
	if parts:
		avg = sum(parts) / len(parts)
		while len(parts) < segs:
			parts.append(avg)
		return [flt(x) for x in parts[:segs]]
	if tw > 0:
		return [tw / segs] * segs
	return [0.0] * segs


def _planned_qty_for_roll_line(job_row, roll_index: int, segs: int) -> float:
	"""Planned qty = net weight (kg) for this combination segment (e.g. 48\"→89.61, 37\"→69.08)."""
	if segs < 1:
		segs = 1
	seg_weights = _segment_weights_kg(job_row, segs)
	seg_i = roll_index % segs
	seg_kg = seg_weights[seg_i] if seg_i < len(seg_weights) else 0.0
	return round(flt(seg_kg), 3)


@frappe.whitelist()
def get_next_spr_batch_numbers(
	shaft_production_run,
	count,
	client_max_roll=None,
	run_date=None,
	custom_unit=None,
	shift=None,
):
	"""
	Preview batch/roll numbers for new rows (e.g. after Create Entry) without submitting SPR.
	Requires run_date, custom_unit, shift. Optional client_max_roll = highest roll index already on the form.

	Pass run_date, custom_unit, shift from the desk form when the document is saved but header
	fields were just edited and not yet re-saved — otherwise get_doc() would see stale DB values.
	"""
	count = cint(count)
	if count < 1:
		return []
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save the Shaft Production Run first"))
	doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	if run_date not in (None, ""):
		doc.run_date = run_date
	if custom_unit not in (None, "") and str(custom_unit).strip():
		doc.custom_unit = custom_unit
	if shift not in (None, "") and str(shift).strip():
		doc.shift = shift
	rd_val = doc.run_date
	cu = _cstr(doc.get("custom_unit"))
	sh = _cstr(doc.shift)
	if not rd_val or not cu or not sh:
		frappe.throw(_("Set Run Date, Unit, and Shift to assign batch numbers."))
	rd = getdate(rd_val)
	unit_d = doc._unit_digit()
	root_5 = f"{rd.month:02d}{unit_d}{rd.year % 100:02d}"
	series_prefix = doc._resolve_series_prefix(root_5)
	next_roll = doc._next_roll_starting(series_prefix)
	try:
		if client_max_roll is not None and cint(client_max_roll) >= 0:
			next_roll = max(int(next_roll), cint(client_max_roll) + 1)
	except Exception:
		pass
	item_meta = frappe.get_meta("Shaft Production Run Item")
	out = []
	for _i in range(count):
		bn = f"{series_prefix}/{next_roll}"
		rf = item_meta.get_field("roll_no")
		rn = int(next_roll) if rf and rf.fieldtype == "Int" else str(next_roll)
		out.append({"batch_no": bn, "roll_no": rn})
		next_roll += 1
	return out


@frappe.whitelist()
def build_spr_roll_result_lines_for_job(shaft_production_run, job_id):
	"""
	Build Roll Production Result (SPR Item) lines for one job.
	
	✅ CORRECT: Extract GSM and WIDTH from Item Name, then match exactly.
	Combination "33+63" cycles rolls through widths [33, 63, 33, 63, ...]
	Each roll matched to correct WO by (GSM, WIDTH) tuple lookup.
	"""
	if not job_id:
		frappe.throw(_("Job ID is required"))
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save Shaft Production Run first"))
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Production Plan not found on this Shaft Production Run"))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	job_row = None
	for j in _spr_job_rows(spr_doc):
		if _spr_job_keys_match(_spr_job_id(j), job_id):
			job_row = j
			break
	if not job_row:
		frappe.throw(_("Job {0} not found in Available Jobs").format(job_id))

	no_shafts = int(flt(getattr(job_row, "no_of_shafts", 0) or 0))
	if no_shafts < 1:
		no_shafts = 1
	comb = getattr(job_row, "combination", None) or ""
	segs = _count_combination_segments(comb)
	n_rolls = max(1, no_shafts * segs)

	shaft_combination = get_shaft_combination(pp_name, job_id)
	if getattr(job_row, "combination", None) and not shaft_combination:
		shaft_combination = job_row.combination

	wo_list = _get_work_orders_for_spr_job(pp_name, spr_doc, job_row)
	if not wo_list:
		frappe.throw(_("No Work Orders for job {0} on this Production Plan").format(job_id))

	# Extract job GSM
	job_gsm = None
	if getattr(job_row, "gsm", None) not in (None, 0, "0"):
		try:
			job_gsm = int(flt(job_row.gsm))
		except Exception:
			pass
	
	# Parse combination to get individual widths (e.g., "33+63" → [33, 63])
	individual_widths = []
	if comb:
		try:
			width_parts = comb.split("+")
			individual_widths = [flt(w.strip()) for w in width_parts if w.strip()]
		except Exception:
			frappe.logger().warning(f"[SPR] Could not parse combination '{comb}' for job {job_id}")
	
	# ✅ DEDUPLICATE: For "63+63", use only UNIQUE widths → ONE WO per unique width (avoids duplicate WOs)
	# Map: unique_width → width_index (position of FIRST occurrence)
	width_to_first_idx = {}
	for idx, w in enumerate(individual_widths):
		if w not in width_to_first_idx:
			width_to_first_idx[w] = idx
	
	# ✅ NEW: Build (GSM, WIDTH) → WO map from Item Names (NOT item codes)
	gsm_width_to_wo = _build_gsm_width_to_wo_map_from_item_names(wo_list)
	
	lines = []
	for idx in range(n_rolls):
		# Get individual width for this roll
		individual_width = None
		if individual_widths:
			individual_width = individual_widths[idx % len(individual_widths)]
		
		# ✅ EXACT MATCH: (GSM, WIDTH) from item name
		wo = None
		if job_gsm is not None and individual_width is not None:
			key = (job_gsm, individual_width)
			if key in gsm_width_to_wo:
				wo = gsm_width_to_wo[key]
				frappe.logger().info(f"[SPR] Roll {idx+1}: GSM {job_gsm} + Width {individual_width}\" → WO {wo['name']}")
		
		# Fallback: Use first WO (shouldn't happen with verified PP)
		if wo is None:
			wo = wo_list[0]
			frappe.logger().warning(f"[SPR WARNING] No exact match for GSM {job_gsm}, Width {individual_width}, using {wo['name']}")
		if job_gsm:
			row["gsm"] = job_gsm
		if getattr(job_row, "meter_roll_mtrs", None) not in (None, 0, ""):
			row["meter_roll"] = flt(job_row.meter_roll_mtrs)
		lines.append(row)
	return lines


def _build_gsm_width_to_wo_map_from_item_names(wo_list: list) -> dict:
	"""
	✅ Extract GSM and WIDTH from Item Code (the source of truth).
	Item Code format: "1001050010251600"
	  - Positions [9:12] = GSM (e.g., "025" = 25)
	  - Positions [12:16] = WIDTH in MM (e.g., "1600" = 1600mm = 63 inches)
	
	Returns: {(25, 63.0): WO, (90, 63.0): WO, ...}
	Keeps FIRST occurrence of each (GSM, WIDTH) pair.
	"""
	gsm_width_to_wo = {}
	
	for wo in wo_list:
		try:
			production_item = frappe.db.get_value("Work Order", wo["name"], "production_item")
			if not production_item:
				frappe.logger().warning(f"[WO MAP] No production_item for WO {wo['name']}")
				continue
			
			# ✅ Parse item code to get GSM and WIDTH (SOURCE OF TRUTH)
			gsm, width = parse_item_code(_cstr(production_item))
			
			if gsm > 0 and width > 0:
				key = (gsm, width)
				# ✅ KEEP FIRST OCCURRENCE: Don't overwrite if key already exists
				if key not in gsm_width_to_wo:
					gsm_width_to_wo[key] = wo
					frappe.logger().info(f"[WO MAP] {wo['name']} → GSM {gsm} + WIDTH {width}\" (from item code: {production_item})")
				else:
					# Duplicate width found - log it but keep first WO
					frappe.logger().info(f"[WO MAP] Note: {wo['name']} also has GSM {gsm} + WIDTH {width}\", but keeping first WO {gsm_width_to_wo[key]['name']}")
			else:
				frappe.logger().warning(f"[WO MAP] Could not parse item code {production_item} (GSM={gsm}, WIDTH={width})")
		
		except Exception as e:
			frappe.logger().warning(f"[WO MAP ERROR] WO {wo.get('name')}: {str(e)}")
	
	return gsm_width_to_wo


@frappe.whitelist()
def get_job_rows_for_production_plan(production_plan):
	if not production_plan:
		return []
	if not frappe.db.exists("Production Plan", production_plan):
		frappe.throw(_("Production Plan {0} not found").format(production_plan))
	custom_sd = _build_shaft_jobs_from_custom_shaft_details(production_plan)
	if custom_sd is not None:
		return custom_sd
	detailed = _build_shaft_jobs_from_pp_details(production_plan)
	if detailed is not None:
		return detailed
	rows = frappe.db.sql(
		"""
		SELECT wo.production_plan_item AS job_no, SUM(wo.qty) AS total_weight
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		  AND IFNULL(wo.production_plan_item, '') != ''
		GROUP BY wo.production_plan_item
		ORDER BY MIN(wo.creation)
		""",
		{"pp": production_plan},
		as_dict=True,
	)
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out = []
	for i, r in enumerate(rows):
		row = {"job_id": r.job_no, "total_weight": flt(r.total_weight)}
		if job_meta.has_field("production_plan_item"):
			row["production_plan_item"] = r.job_no
		comb = None
		if job_meta.has_field("combination"):
			comb = get_shaft_combination(production_plan, r.job_no)
			if comb:
				row["combination"] = comb
		m = dict(row)
		wos = _resolve_wos_for_pp_job_row(
			production_plan,
			ppi=m.get("production_plan_item"),
			job_id=_cstr(m.get("job_id")),
			row_index=i,
			combination=m.get("combination"),
		)
		if job_meta.has_field("work_orders") and wos:
			row["work_orders"] = ", ".join(w["name"] for w in wos)
		out.append(row)
	return out


def _spr_job_rows(spr_doc):
	return getattr(spr_doc, "shaft_jobs", None) or getattr(spr_doc, "jobs", None) or []


def _spr_job_id(job):
	return getattr(job, "job_id", None) or getattr(job, "job_no", None)


def _spr_shaft_job_for_roll(spr_doc, job_id_str):
	pid = _cstr(job_id_str)
	if not pid:
		return None
	for sj in _spr_job_rows(spr_doc):
		if _spr_job_keys_match(_spr_job_id(sj), pid):
			return sj
		if _cstr(getattr(sj, "production_plan_item", None)) == pid:
			return sj
	return None


def _spr_numeric_str_ok_for_eq(s: str) -> bool:
	s = (s or "").strip()
	if not s:
		return False
	try:
		float(s)
		return True
	except ValueError:
		return False


def _spr_job_keys_match(a, b) -> bool:
	"""Match job ids across 1 / 1.0 / '1 ' and identical non-numeric strings."""
	na = _cstr(a)
	nb = _cstr(b)
	if na == nb:
		return True
	if not na or not nb:
		return False
	if _spr_numeric_str_ok_for_eq(na) and _spr_numeric_str_ok_for_eq(nb):
		return flt(na) == flt(nb)
	return False


def _spr_item_roll_matches_bundle_job(sj, it, job_id: str) -> bool:
	if _spr_job_keys_match(getattr(it, "job", None), job_id):
		return True
	if sj:
		jj = _cstr(getattr(it, "job", None))
		ppi = _cstr(getattr(sj, "production_plan_item", None))
		if ppi and jj == ppi:
			return True
	return False


def _spr_resolve_item_job_to_canonical_id(spr_doc, it) -> str:
	"""Map a roll line's job field to shaft_jobs job_id (handles numeric drift + PP item name)."""
	raw = _cstr(getattr(it, "job", None))
	if not raw:
		return ""
	for sj in _spr_job_rows(spr_doc):
		canon = _cstr(_spr_job_id(sj))
		if _spr_job_keys_match(raw, canon):
			return canon
		ppi = _cstr(getattr(sj, "production_plan_item", None))
		if ppi and raw == ppi:
			return canon
	return raw


def _spr_job_product_code(sj):
	"""Product item from Available Jobs: manual_items, else Work Order production_item."""
	if not sj:
		return ""
	mi = _cstr(getattr(sj, "manual_items", None) or "").strip()
	if mi:
		return mi
	wos = _cstr(getattr(sj, "work_orders", None) or "")
	for raw in wos.replace("\n", ",").split(","):
		wo = raw.strip()
		if wo and frappe.db.exists("Work Order", wo):
			pi = frappe.db.get_value("Work Order", wo, "production_item")
			if pi:
				return _cstr(pi)
	return ""


def _spr_bundle_job_label(sj):
	jid = _cstr(_spr_job_id(sj))
	comb = _cstr(getattr(sj, "combination", None) or "").strip()
	if comb:
		return f"Job {jid} — {comb}"
	prod = _spr_job_product_code(sj) or ""
	if prod:
		return f"Job {jid} — {prod}"
	return f"Job {jid}"


def _spr_bundle_segment_widths_for_job(spr_doc, sj) -> list[float]:
	"""Per-job width options for Bundle Packaging: combination segments / WO item widths / existing roll widths."""
	out: list[float] = []
	if not sj:
		return out
	comb = _cstr(getattr(sj, "combination", None) or "")
	for w in _parse_combination_widths_inches(comb):
		fw = flt(w)
		if fw > 0 and fw not in out:
			out.append(fw)
	for wo in _get_work_orders_for_spr_job(get_pp_from_spr(spr_doc.name), spr_doc, sj):
		wo_name = _cstr(wo.get("name"))
		if not wo_name:
			continue
		item_code = frappe.db.get_value("Work Order", wo_name, "production_item")
		_gsm, width_inch = parse_item_code(item_code)
		fw = flt(width_inch)
		if fw > 0 and fw not in out:
			out.append(fw)
	jid = _cstr(_spr_job_id(sj))
	for it in spr_doc.items or []:
		if not _spr_item_roll_matches_bundle_job(sj, it, jid):
			continue
		fw = flt(getattr(it, "width_inch", None))
		if fw > 0 and fw not in out:
			out.append(fw)
	if not out:
		tw = flt(getattr(sj, "total_width", None))
		if tw > 0:
			out.append(tw)
	return sorted(set(out))


def _spr_bundle_job_segments_detail(spr_doc, sj) -> list[dict]:
	"""Per combination segment: width, net kg/shaft, linked WO item — for Bundle packaging UI."""
	if not sj:
		return []
	pp_name = get_pp_from_spr(spr_doc.name)
	comb = getattr(sj, "combination", None)
	segs = max(1, _count_combination_segments(comb))
	widths = _parse_combination_widths_inches(comb) if comb else []
	weights = _segment_weights_kg(sj, segs)
	wos = _get_work_orders_for_spr_job(pp_name, spr_doc, sj)
	out: list[dict] = []
	for i in range(segs):
		w_seg = flt(widths[i]) if i < len(widths) else flt(getattr(sj, "total_width", None))
		if w_seg <= 0:
			continue
		nk = weights[i] if i < len(weights) else None
		item_code = ""
		item_name = ""
		for wo in wos:
			won = _cstr(wo.get("name"))
			if not won:
				continue
			ic = frappe.db.get_value("Work Order", won, "production_item")
			if not ic:
				continue
			_g, w_item = parse_item_code(ic)
			if abs(flt(w_item) - w_seg) <= 0.75:
				item_code = _cstr(ic)
				item_name = _cstr(frappe.db.get_value("Item", ic, "item_name") or "")
				break
		out.append(
			{
				"width_inch": round(w_seg, 1),
				"net_kg_per_shaft": round(flt(nk), 3) if nk is not None else None,
				"item_code": item_code,
				"item_name": item_name,
			}
		)
	return out


def _spr_roll_effective_width_inch(it) -> float:
	"""Roll line width: prefer stored width_inch; else derive from item_code (handles total-width on row)."""
	rw = flt(getattr(it, "width_inch", None))
	if rw > 0.001:
		return rw
	ic = getattr(it, "item_code", None)
	if ic:
		_g, w = parse_item_code(ic)
		if flt(w) > 0.001:
			return flt(w)
	return 0.0


def _spr_roll_matches_bundle_width(it, width_inch: float, job_w: float) -> bool:
	"""Match roll to selected segment width; use item_code width when stored width is total or zero."""
	rw = _spr_roll_effective_width_inch(it)
	wx = flt(width_inch)
	jw = flt(job_w)
	tol = 0.75
	if rw > 0.001:
		return abs(rw - wx) <= tol
	if jw > 0.001 and wx > 0.001:
		return abs(jw - wx) <= tol
	return False


def _spr_item_line_from_wo(pp_name, job_id, shaft_combination, planned_qty, wo):
	wo_doc = frappe.get_doc("Work Order", wo["name"])
	item_code = wo_doc.production_item
	item_name = frappe.db.get_value("Item", item_code, "item_name")
	gsm, width_inch = parse_item_code(item_code)
	quality, color = extract_quality_and_color(item_name or "")
	return {
		"work_order": wo["name"],
		"item_code": item_code,
		"item_name": item_name,
		"quality": quality or None,
		"gsm": gsm,
		"planned_qty": planned_qty,
		"job": job_id,
		"batch_no": "",
		"party_code": get_order_code(wo_doc),
		"uom": _item_stock_uom_for_spr(item_code),
		"roll_no": 0,
		"meter_roll": 0,
		"net_weight": 0,
		"gross_weight": 0,
		"width_inch": width_inch,
		"color": color or None,
	}


def _build_spr_items_from_pp(spr_doc, pp_name):
	items = []
	for job in _spr_job_rows(spr_doc):
		job_id = _spr_job_id(job)
		if not job_id:
			continue
		shaft_combination = get_shaft_combination(pp_name, job_id)
		if getattr(job, "combination", None) and not shaft_combination:
			shaft_combination = job.combination
		planned_qty = getattr(job, "total_weight", None) or 0
		for wo in _get_work_orders_for_spr_job(pp_name, spr_doc, job):
			items.append(_spr_item_line_from_wo(pp_name, job_id, shaft_combination, planned_qty, wo))
	return items


def _build_roll_items_from_spr(spr_doc, pp_name, job_id_filter=None):
	items = []
	for job in _spr_job_rows(spr_doc):
		job_id = _spr_job_id(job)
		if not job_id:
			continue
		if job_id_filter is not None and _cstr(job_id) != _cstr(job_id_filter):
			continue
		shaft_combination = get_shaft_combination(pp_name, job_id)
		if getattr(job, "combination", None) and not shaft_combination:
			shaft_combination = job.combination
		planned_qty = getattr(job, "total_weight", None) or 0
		for wo in _get_work_orders_for_spr_job(pp_name, spr_doc, job):
			wo_doc = frappe.get_doc("Work Order", wo["name"])
			item_code = wo_doc.production_item
			item_name = frappe.db.get_value("Item", item_code, "item_name")
			gsm, width_inch = parse_item_code(item_code)
			items.append(
				{
					"job_no": job_id,
					"shaft_combination": shaft_combination,
					"planned_qty": planned_qty,
					"wo_id": wo["name"],
					"item_code": item_code,
					"item_name": item_name,
					"gsm": gsm,
					"width_inches": width_inch,
					"order_code": get_order_code(wo_doc),
					"batch_no": "",
					"roll_no": "",
					"meter_per_roll": 0,
					"net_weight": 0,
					"gross_weight": 0,
				}
			)
	return items


@frappe.whitelist()
def get_item_rows_for_production_plan(production_plan):
	"""Build SPR Item rows from WOs for all jobs (API / legacy). Desk flow uses build_spr_roll_result_lines_for_job per job."""
	if not production_plan:
		return []
	jobs = get_job_rows_for_production_plan(production_plan)
	spr = frappe._dict(shaft_jobs=[])
	for j in jobs:
		spr.shaft_jobs.append(frappe._dict(job_id=j["job_id"], total_weight=j.get("total_weight")))
	return _build_spr_items_from_pp(spr, production_plan)


@frappe.whitelist()
def get_or_create_roll_entry(shaft_production_run):
	"""All jobs on SPR (legacy API). Prefer get_or_create_roll_entry_for_job from shaft_jobs row."""
	existing = frappe.db.get_value(
		"Roll Production Entry",
		{"shaft_production_run": shaft_production_run, "docstatus": ["!=", 2]},
		"name",
	)
	if existing:
		return {"existing": existing}
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Could not find Production Plan linked to {0}").format(shaft_production_run))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	items = _build_roll_items_from_spr(spr_doc, pp_name)
	return {"production_plan": pp_name, "items": items}


@frappe.whitelist()
def get_or_create_roll_entry_for_job(shaft_production_run, job_id):
	"""Open/create Roll Production Entry for a single PP job (shaft + combination from shaft_jobs row)."""
	if not job_id:
		frappe.throw(_("Job ID is required"))
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save Shaft Production Run first"))
	meta_rpe = frappe.get_meta("Roll Production Entry")
	filters = {
		"shaft_production_run": shaft_production_run,
		"docstatus": ["!=", 2],
	}
	if meta_rpe.has_field("job_id"):
		filters["job_id"] = _cstr(job_id)
	existing = frappe.db.get_value("Roll Production Entry", filters, "name")
	if existing:
		return {"existing": existing, "job_id": _cstr(job_id)}
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Could not find Production Plan linked to {0}").format(shaft_production_run))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	items = _build_roll_items_from_spr(spr_doc, pp_name, job_id_filter=job_id)
	if not items:
		frappe.throw(
			_("No roll lines for job {0}. Check Work Orders for this Production Plan.").format(job_id)
		)
	return {
		"production_plan": pp_name,
		"items": items,
		"job_id": _cstr(job_id),
	}


def get_pp_from_spr(spr_name):
	pp_field = frappe.db.get_value("Shaft Production Run", spr_name, "production_plan")
	if pp_field:
		return pp_field
	if spr_name.startswith("SPR-"):
		return spr_name[4:]
	return None


def get_shaft_combination(pp_name, job_no):
	if frappe.db.exists("DocType", "Production Plan Shaft Detail"):
		v = frappe.db.get_value(
			"Production Plan Shaft Detail",
			{"parent": pp_name, "job_no": job_no},
			"shaft_combination",
		)
		if v:
			return v
	child_dt = _production_plan_custom_shaft_child_doctype()
	if child_dt:
		meta_child = frappe.get_meta(child_dt)
		if meta_child.has_field("s_no"):
			s_no_candidates = [job_no]
			try:
				s_no_candidates.append(cint(job_no))
			except Exception:
				pass
			for candidate in s_no_candidates:
				if candidate is None or candidate == "":
					continue
				v = frappe.db.get_value(child_dt, {"parent": pp_name, "s_no": candidate}, "combination")
				if v:
					return v
		for jf in ("job", "job_no", "job_id"):
			if not meta_child.has_field(jf):
				continue
			v = frappe.db.get_value(child_dt, {"parent": pp_name, jf: job_no}, "shaft_combination")
			if v:
				return v
			if meta_child.has_field("combination"):
				v = frappe.db.get_value(child_dt, {"parent": pp_name, jf: job_no}, "combination")
				if v:
					return v
	return ""


def _production_plan_item_row_names_ordered(pp_name: str) -> list[str]:
	"""Production Plan Item row `name` values in table order (matches WO.production_plan_item)."""
	if not pp_name or not frappe.db.exists("Production Plan", pp_name):
		return []
	if not frappe.db.exists("DocType", "Production Plan Item"):
		return []
	rows = frappe.db.sql(
		"""
		SELECT name FROM `tabProduction Plan Item`
		WHERE parent = %(p)s
		ORDER BY idx ASC, name ASC
		""",
		{"p": pp_name},
	)
	return [_cstr(r[0]) for r in rows if r[0]]


def _resolve_job_ref_to_production_plan_item(pp_name: str, job_ref: str) -> str | None:
	"""
	Map human job id (1, 2, … from s_no) to the correct Production Plan Item row name.
	Work Orders link via production_plan_item = PPI row name, not the display job number.
	When the PP has only one line, every shaft job row maps to that line (same WO for multiple SPR jobs).
	"""
	names = _production_plan_item_row_names_ordered(pp_name)
	if not names:
		return None
	t = _cstr(job_ref).strip()
	if not t:
		return None
	if t in names:
		return t
	if len(names) == 1:
		if t.isdigit():
			return names[0]
		return None
	if t.isdigit():
		n = int(t)
		if 1 <= n <= len(names):
			return names[n - 1]
	return None


def get_work_orders_for_job(pp_name, job_no):
	if not pp_name or job_no is None:
		return []
	jn = _cstr(job_no).strip()
	if not jn:
		return []
	wos = frappe.db.sql(
		"""
		SELECT wo.name, wo.production_item, wo.qty as planned_qty, wo.produced_qty, wo.status
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp_name)s
		  AND wo.production_plan_item = %(job_no)s
		  AND wo.docstatus != 2
		ORDER BY wo.name
		""",
		{"pp_name": pp_name, "job_no": jn},
		as_dict=True,
	)
	if wos:
		return wos
	pi = _resolve_job_ref_to_production_plan_item(pp_name, jn)
	if pi and pi != jn:
		return get_work_orders_for_job(pp_name, pi)
	return []


def parse_item_code(item_code):
	try:
		if len(item_code) >= 16:
			gsm = int(item_code[9:12])
			width_mm = int(item_code[12:16])
			width_inch = round(width_mm / 25.4, 1)
			return gsm, width_inch
	except Exception:
		pass
	return 0, 0


def _item_stock_uom_for_spr(item_code: str) -> str:
	"""Resolve a valid UOM Link for Shaft Production Run Item (prefer Item.stock_uom, usually Kg)."""
	if not item_code:
		return "Kg"
	u = frappe.db.get_value("Item", item_code, "stock_uom")
	u = (u or "").strip()
	if u and frappe.db.exists("UOM", u):
		return u
	for cand in ("Kg", "kg", "Kgs", "KG"):
		if frappe.db.exists("UOM", cand):
			return cand
	return u or "Kg"


# Manual job + bundle packaging (Actions on Shaft Production Run)
SPR_MANUAL_SOURCE_WH = "Raw Materials - JSB-1ZT"
SPR_MANUAL_FG_WH = "Finished Goods - JSB-1ZT"


def _spr_require_saved(spr_name: str):
	if not spr_name or not frappe.db.exists("Shaft Production Run", spr_name):
		frappe.throw(_("Save the Shaft Production Run first"))


def _spr_pp_and_company(spr_name: str):
	pp_name = get_pp_from_spr(spr_name)
	if not pp_name:
		frappe.throw(_("Set Production Plan on this Shaft Production Run"))
	doc = frappe.get_doc("Shaft Production Run", spr_name)
	company = doc.get("company") or frappe.db.get_value("Production Plan", pp_name, "company")
	if not company:
		company = frappe.defaults.get_user_default("Company") or frappe.db.get_single_value(
			"Global Defaults", "default_company"
		)
	if not company:
		frappe.throw(_("Company could not be resolved"))
	return pp_name, company, doc


def _spr_warehouses_exist():
	for wh in (SPR_MANUAL_SOURCE_WH, SPR_MANUAL_FG_WH):
		if not frappe.db.exists("Warehouse", wh):
			frappe.throw(_("Warehouse {0} not found. Create it or update SPR_MANUAL_* constants.").format(wh))


def _spr_is_manual_shaft_job(sj) -> bool:
	return cint(getattr(sj, "is_manual", 0) or 0) == 1


def _spr_net_kg_per_shaft_for_pp_line_width(
	spr_doc, width_inch: float, production_plan_item: str | None
) -> tuple[float | None, str | None]:
	"""
	Match item width (inch) to a segment in Available Jobs (non-manual): kg per shaft for that segment.
	Uses combination widths + net_weight split, or total_width for single-segment jobs.
	"""
	wx = flt(width_inch)
	if wx <= 0:
		return None, None
	ppi = _cstr(production_plan_item) if production_plan_item else ""
	rows = list(_spr_job_rows(spr_doc))
	preferred = [
		sj
		for sj in rows
		if not _spr_is_manual_shaft_job(sj) and ppi and _cstr(getattr(sj, "production_plan_item", None)) == ppi
	]
	candidates = preferred if preferred else [sj for sj in rows if not _spr_is_manual_shaft_job(sj)]
	for sj in candidates:
		comb = getattr(sj, "combination", None)
		segs = max(1, _count_combination_segments(comb))
		widths = _parse_combination_widths_inches(comb) if comb else []
		weights = _segment_weights_kg(sj, segs)
		jid = _cstr(_spr_job_id(sj))
		if segs > 1 and len(widths) >= segs:
			for i in range(segs):
				if abs(flt(widths[i]) - wx) <= 0.5:
					if i < len(weights) and flt(weights[i]) > 0:
						return flt(weights[i]), jid
			continue
		tw = flt(getattr(sj, "total_width", None))
		if tw > 0 and abs(tw - wx) <= 0.5 and weights:
			return flt(weights[0]), jid
	return None, None


def _spr_try_submit_manual_work_order(wo_name: str):
	"""Submit Work Order when possible so manufacturing can start (best-effort)."""
	try:
		wo = frappe.get_doc("Work Order", wo_name)
		if wo.docstatus == 0:
			wo.submit()
	except Exception:
		frappe.log_error(
			title=f"SPR manual job: could not submit Work Order {wo_name}",
			message=frappe.get_traceback(),
		)


def _spr_insert_manual_work_order(
	pp,
	company: str,
	item_code: str,
	production_plan_item: str,
	ppi_row,
	qty: float,
) -> str:
	"""Always insert a new Work Order for manual job flow (no reuse of existing WO)."""
	from production_entry.production_planning.doctype.planning_sheet.planning_sheet import (
		get_default_bom_for_item,
	)

	bom = get_default_bom_for_item(item_code, company)
	if not bom:
		frappe.throw(_("No active BOM for item {0}").format(item_code))
	pp_name = pp.name
	wo = frappe.new_doc("Work Order")
	wo.production_item = item_code
	wo.bom_no = bom
	wo.qty = flt(qty)
	wo.company = company
	wo.production_plan = pp_name
	# Leave production_plan_item unset on insert so site "one WO per PP line" Server Scripts
	# do not block additional SPR manual Work Orders. Production Plan link stays for traceability.
	wo.production_plan_item = None
	meta_wo = frappe.get_meta("Work Order")
	if meta_wo.has_field("description"):
		wo.description = _("SPR manual job — PP line {0} · Item {1}").format(production_plan_item, item_code)
	if pp.get("sales_order"):
		wo.sales_order = pp.sales_order
	if frappe.get_meta("Work Order").has_field("sales_order_item"):
		wo.sales_order_item = getattr(ppi_row, "sales_order_item", None) or None
	wo.source_warehouse = SPR_MANUAL_SOURCE_WH
	wo.fg_warehouse = SPR_MANUAL_FG_WH
	if frappe.get_meta("Work Order").has_field("wip_warehouse"):
		wip = frappe.db.get_value("Stock Settings", None, "default_wip_warehouse")
		if wip:
			wo.wip_warehouse = wip
	frappe.flags.spr_manual_work_order_insert = True
	try:
		wo.insert(ignore_permissions=True)
	finally:
		frappe.flags.spr_manual_work_order_insert = False
	wo_name = wo.name
	try:
		wo.reload()
		wo.add_comment("Comment", _("SPR manual — Production Plan line {0}").format(production_plan_item))
	except Exception:
		pass
	_spr_try_submit_manual_work_order(wo_name)
	return wo_name


@frappe.whitelist()
def spr_get_manual_job_catalog(shaft_production_run):
	"""Production Plan po_items + width + existing net on SPR by item_code (reuse hint)."""
	_spr_require_saved(shaft_production_run)
	pp_name, company, spr = _spr_pp_and_company(shaft_production_run)
	pp = frappe.get_doc("Production Plan", pp_name)
	out = []
	net_by_item: dict[str, float] = {}
	for it in spr.items or []:
		ic = _cstr(getattr(it, "item_code", None))
		if not ic:
			continue
		net_by_item[ic] = net_by_item.get(ic, 0.0) + flt(getattr(it, "net_weight", None))
	for row in pp.get("po_items") or []:
		ic = _cstr(getattr(row, "item_code", None))
		if not ic:
			continue
		item_name = frappe.db.get_value("Item", ic, "item_name")
		gsm, width_inch = parse_item_code(ic)
		first_seg_kg = None
		for sj in _spr_job_rows(spr):
			if _cstr(getattr(sj, "production_plan_item", None)) == _cstr(row.name):
				segs = max(1, _count_combination_segments(getattr(sj, "combination", None)))
				segw = _segment_weights_kg(sj, segs)
				if segw:
					first_seg_kg = round(flt(segw[0]), 3)
				break
		if first_seg_kg is None:
			for sj in _spr_job_rows(spr):
				if _spr_job_product_code(sj) != ic:
					continue
				segs = max(1, _count_combination_segments(getattr(sj, "combination", None)))
				segw = _segment_weights_kg(sj, segs)
				if segw:
					first_seg_kg = round(flt(segw[0]), 3)
				break
		net_ps, mj = _spr_net_kg_per_shaft_for_pp_line_width(spr, width_inch, row.name)
		out.append(
			{
				"item_code": ic,
				"item_name": item_name or ic,
				"production_plan_item": row.name,
				"planned_qty": flt(getattr(row, "planned_qty", None)),
				"gsm": gsm,
				"width_inch": width_inch,
				"existing_net_weight_kg": round(net_by_item.get(ic, 0.0), 2),
				"first_segment_planned_kg": first_seg_kg,
				"net_per_shaft_kg": round(net_ps, 3) if net_ps is not None else None,
				"matched_job_id": mj,
			}
		)
	return {"production_plan": pp_name, "company": company, "lines": out}


@frappe.whitelist()
def spr_create_manual_job(
	shaft_production_run,
	item_code,
	production_plan_item,
	no_of_shafts,
	wo_qty=None,
):
	"""Create draft Work Order + append manual Shaft Production Run Job row."""
	item_code = _cstr(item_code)
	production_plan_item = _cstr(production_plan_item)
	no_of_shafts = cint(no_of_shafts)
	if no_of_shafts < 1:
		frappe.throw(_("Number of shafts must be at least 1"))
	if not item_code or not production_plan_item:
		frappe.throw(_("Item and Production Plan line are required"))

	_spr_require_saved(shaft_production_run)
	pp_name, company, spr = _spr_pp_and_company(shaft_production_run)
	_spr_warehouses_exist()

	pp = frappe.get_doc("Production Plan", pp_name)
	ppi_row = None
	for r in pp.get("po_items") or []:
		if _cstr(r.name) == production_plan_item and _cstr(r.item_code) == item_code:
			ppi_row = r
			break
	if not ppi_row:
		frappe.throw(_("Production Plan item line not found for this item"))

	qty = flt(wo_qty) if wo_qty is not None and str(wo_qty).strip() != "" else None
	if qty is None or qty <= 0:
		qty = flt(getattr(ppi_row, "planned_qty", None) or 0) or 1.0

	wo_name = _spr_insert_manual_work_order(pp, company, item_code, production_plan_item, ppi_row, qty)

	spr.reload()
	for j in _spr_job_rows(spr):
		wos = _cstr(getattr(j, "work_orders", None) or "")
		for part in wos.replace("\n", ",").split(","):
			if part.strip() == wo_name:
				frappe.throw(
					_("Work Order {0} is already linked to this Shaft Production Run (Job {1}).").format(
						wo_name,
						_spr_job_id(j),
					)
				)

	job_id = f"MAN-{frappe.generate_hash(length=6).upper()}"
	for _attempt in range(20):
		if not any(_cstr(_spr_job_id(j)) == job_id for j in _spr_job_rows(spr)):
			break
		job_id = f"MAN-{frappe.generate_hash(length=6).upper()}"

	gsm, width_inch = parse_item_code(item_code)
	item_name = frappe.db.get_value("Item", item_code, "item_name")
	quality, color = extract_quality_and_color(item_name or "")

	row = {
		"job_id": job_id,
		"production_plan_item": production_plan_item,
		"is_manual": 1,
		"no_of_shafts": no_of_shafts,
		"work_orders": wo_name,
		"total_weight": qty,
	}
	meta = frappe.get_meta("Shaft Production Run Job")
	if meta.has_field("gsm") and gsm:
		try:
			row["gsm"] = int(gsm)
		except Exception:
			row["gsm"] = gsm
	if meta.has_field("quality") and quality:
		row["quality"] = quality
	if meta.has_field("combination") and color:
		row["combination"] = color
	if meta.has_field("total_width"):
		row["total_width"] = width_inch
	if meta.has_field("manual_items"):
		row["manual_items"] = item_code

	spr.reload()
	spr.append("shaft_jobs", row)
	spr.save(ignore_permissions=True)

	return {
		"work_order": wo_name,
		"job_id": job_id,
		"shaft_production_run": spr.name,
	}


@frappe.whitelist()
def spr_create_manual_jobs_multi(shaft_production_run, no_of_shafts, items):
	"""
	Create one new Work Order per selected Production Plan line; one manual Available Jobs row.
	items: list of { item_code, production_plan_item, wo_qty } (wo_qty = manufacturing qty in Kg, e.g. net/shaft × shafts).
	"""
	no_of_shafts = cint(no_of_shafts)
	if no_of_shafts < 1:
		frappe.throw(_("Number of shafts must be at least 1"))
	if isinstance(items, str):
		items = frappe.parse_json(items)
	if not items or not isinstance(items, list):
		frappe.throw(_("Select at least one Production Plan line"))

	_spr_require_saved(shaft_production_run)
	pp_name, company, spr = _spr_pp_and_company(shaft_production_run)
	_spr_warehouses_exist()
	pp = frappe.get_doc("Production Plan", pp_name)

	wo_names: list[str] = []
	qtys: list[float] = []
	widths_list: list[float] = []
	item_codes_list: list[str] = []
	ppi_rows = []

	for raw in items:
		if not isinstance(raw, dict):
			frappe.throw(_("Invalid line payload"))
		item_code = _cstr(raw.get("item_code"))
		production_plan_item = _cstr(raw.get("production_plan_item"))
		qty = flt(raw.get("wo_qty"))
		if not item_code or not production_plan_item or qty <= 0:
			frappe.throw(_("Each line needs item, Production Plan row, and Work Order qty greater than zero"))
		ppi_row = None
		for r in pp.get("po_items") or []:
			if _cstr(r.name) == production_plan_item and _cstr(r.item_code) == item_code:
				ppi_row = r
				break
		if not ppi_row:
			frappe.throw(_("Production Plan item line not found for {0}").format(item_code))
		wo_name = _spr_insert_manual_work_order(pp, company, item_code, production_plan_item, ppi_row, qty)
		spr.reload()
		for j in _spr_job_rows(spr):
			wos = _cstr(getattr(j, "work_orders", None) or "")
			for part in wos.replace("\n", ",").split(","):
				if part.strip() == wo_name:
					frappe.throw(
						_("Work Order {0} is already linked to this Shaft Production Run (Job {1}).").format(
							wo_name,
							_spr_job_id(j),
						)
					)
		wo_names.append(wo_name)
		qtys.append(qty)
		item_codes_list.append(item_code)
		ppi_rows.append(ppi_row)
		_gsm, w_in = parse_item_code(item_code)
		widths_list.append(flt(w_in))

	job_id = f"MAN-{frappe.generate_hash(length=6).upper()}"
	for _attempt in range(20):
		if not any(_cstr(_spr_job_id(j)) == job_id for j in _spr_job_rows(spr)):
			break
		job_id = f"MAN-{frappe.generate_hash(length=6).upper()}"

	first_ic = item_codes_list[0]
	gsm, width_inch_one = parse_item_code(first_ic)
	item_name = frappe.db.get_value("Item", first_ic, "item_name")
	quality, color = extract_quality_and_color(item_name or "")

	def _fmt_w(w):
		w = flt(w)
		return str(int(w)) if w == int(w) else str(w)

	comb_str = ""
	if len(widths_list) > 1:
		comb_str = " + ".join([f'{_fmt_w(w)}"' for w in widths_list])
	total_w = sum(widths_list) if widths_list else width_inch_one
	total_qty = sum(qtys)

	row = {
		"job_id": job_id,
		"production_plan_item": _cstr(getattr(ppi_rows[0], "name", None)) if ppi_rows else None,
		"is_manual": 1,
		"no_of_shafts": no_of_shafts,
		"work_orders": ",".join(wo_names),
		"total_weight": total_qty,
	}
	meta = frappe.get_meta("Shaft Production Run Job")
	if meta.has_field("gsm") and gsm:
		try:
			row["gsm"] = int(gsm)
		except Exception:
			row["gsm"] = gsm
	if meta.has_field("quality") and quality:
		row["quality"] = quality
	if meta.has_field("combination"):
		if len(item_codes_list) > 1 and comb_str:
			row["combination"] = comb_str
		elif color:
			row["combination"] = color
	if meta.has_field("total_width"):
		row["total_width"] = total_w
	if meta.has_field("manual_items"):
		row["manual_items"] = ",".join(item_codes_list)

	spr.reload()
	spr.append("shaft_jobs", row)
	spr.save(ignore_permissions=True)

	return {
		"work_orders": wo_names,
		"job_id": job_id,
		"shaft_production_run": spr.name,
	}


@frappe.whitelist()
def spr_get_bundle_packaging_catalog(shaft_production_run):
	"""Jobs from Available Jobs; width options use per-segment widths (combination/WO), then roll widths."""
	_spr_require_saved(shaft_production_run)
	spr = frappe.get_doc("Shaft Production Run", shaft_production_run)
	jobs_out = []
	seen = set()
	for sj in _spr_job_rows(spr):
		jid = _cstr(_spr_job_id(sj))
		if not jid or jid in seen:
			continue
		seen.add(jid)
		jobs_out.append(
			{
				"job_id": jid,
				"label": _spr_bundle_job_label(sj),
				"total_width_available": flt(getattr(sj, "total_width", None)),
				"combination_text": _cstr(getattr(sj, "combination", None) or ""),
				"segments": _spr_bundle_job_segments_detail(spr, sj),
			}
		)
	widths_by_job: dict[str, list] = {j["job_id"]: [] for j in jobs_out}
	for j in jobs_out:
		jid = j["job_id"]
		sj = _spr_shaft_job_for_roll(spr, jid)
		if sj:
			widths_by_job[jid] = _spr_bundle_segment_widths_for_job(spr, sj)
	return {"jobs": jobs_out, "widths_by_job": widths_by_job}


@frappe.whitelist()
def spr_get_bundle_packaging_lines(shaft_production_run):
	"""Deprecated: use spr_get_bundle_packaging_catalog."""
	return spr_get_bundle_packaging_catalog(shaft_production_run)


@frappe.whitelist()
def spr_apply_bundle_packaging_for_job_width(
	shaft_production_run,
	job_id,
	width_inch,
	no_of_packaging,
	whole_gross_kg,
):
	"""Apply same single-roll gross to every roll line matching Job + selected width segment."""
	_spr_require_saved(shaft_production_run)
	job_id = _cstr(job_id)
	width_inch = flt(width_inch)
	no_of_packaging = cint(no_of_packaging)
	whole_gross_kg = flt(whole_gross_kg)
	if no_of_packaging < 1:
		frappe.throw(_("Number of packaging must be at least 1"))
	if whole_gross_kg <= 0:
		frappe.throw(_("Whole gross weight must be greater than zero"))
	if not job_id:
		frappe.throw(_("Select a job from Available Jobs"))
	if width_inch <= 0:
		frappe.throw(_("Select a width (in)"))

	spr = frappe.get_doc("Shaft Production Run", shaft_production_run)
	sj = _spr_shaft_job_for_roll(spr, job_id)
	if not sj:
		frappe.throw(_("Job {0} not found in Available Jobs").format(job_id))

	job_w = width_inch
	matching = []
	for it in spr.items or []:
		if not _spr_item_roll_matches_bundle_job(sj, it, job_id):
			continue
		if _spr_roll_matches_bundle_width(it, width_inch, job_w):
			matching.append(it)

	if not matching:
		for it in spr.items or []:
			if not _spr_item_roll_matches_bundle_job(sj, it, job_id):
				continue
			rw = _spr_roll_effective_width_inch(it)
			if rw > 0.001 and abs(rw - flt(width_inch)) <= 0.75:
				matching.append(it)

	if not matching:
		frappe.throw(
			_(
				"No roll lines for job {0} with width {1} in. Create roll entry or check widths. "
				"(If this is a combination job, pick the segment width that matches the roll item, not total width.)"
			).format(job_id, width_inch)
		)

	single_gross = round(whole_gross_kg / float(no_of_packaging), 2)
	total_width_inch = round(width_inch * float(no_of_packaging), 4)

	for it in matching:
		it.gross_weight = single_gross
		# Only set gross_weight. Net weight auto-calculates via other functions when operator enters it.
		# Do NOT force net_weight here — let Frappe field handlers and auto-calculation manage it.

	avg_n = sum(flt(getattr(it, "net_weight", None)) for it in matching) / len(matching)
	bundle_net = round(avg_n * float(no_of_packaging), 2)

	# Store combination as: NO_OF_PACKAGING * WIDTH INCH (example: 4 * 39 INCH)
	comb_calculated = f"{no_of_packaging} * {width_inch} INCH"
	bs = {
		"combination": comb_calculated,
		"rolls_per_bundle": no_of_packaging,
		"single_roll_gross_weight_kg": single_gross,
		"sticker_width": total_width_inch,
		"sticker_bundle_gross_weight_kg": round(whole_gross_kg, 2),
		"sticker_bundle_weight": bundle_net,
	}
	if frappe.get_meta("Bundle Stickers").has_field("job_id"):
		bs["job_id"] = job_id or None
	spr.append("bundle_stickers", bs)
	spr.save(ignore_permissions=True)

	return {
		"updated_rolls": len(matching),
		"single_roll_gross_kg": single_gross,
		"total_width_inch": total_width_inch,
		"sticker_bundle_weight_kg": bundle_net,
	}


@frappe.whitelist()
def spr_apply_bundle_packaging(
	shaft_production_run,
	spr_item_row_name,
	no_of_packaging,
	whole_gross_kg,
):
	"""Single-roll gross on matched line + Bundle Stickers row (Kg / inch)."""
	_spr_require_saved(shaft_production_run)
	no_of_packaging = cint(no_of_packaging)
	whole_gross_kg = flt(whole_gross_kg)
	if no_of_packaging < 1:
		frappe.throw(_("Number of packaging must be at least 1"))
	if whole_gross_kg <= 0:
		frappe.throw(_("Whole gross weight must be greater than zero"))
	if not spr_item_row_name:
		frappe.throw(_("Select a roll line"))

	spr = frappe.get_doc("Shaft Production Run", shaft_production_run)
	target = None
	for it in spr.items or []:
		if _cstr(it.name) == _cstr(spr_item_row_name):
			target = it
			break
	if not target:
		frappe.throw(_("Roll line not found"))

	jid = _cstr(getattr(target, "job", None))
	sj = _spr_shaft_job_for_roll(spr, jid)
	sel_w = flt(getattr(sj, "total_width", None)) if sj else 0.0
	if sel_w <= 0:
		sel_w = flt(getattr(target, "width_inch", None))
	single_gross = round(whole_gross_kg / float(no_of_packaging), 2)
	total_width_inch = round(sel_w * float(no_of_packaging), 4)
	net_one = flt(getattr(target, "net_weight", None))
	bundle_net = round(net_one * float(no_of_packaging), 2)

	target.gross_weight = single_gross

	comb = ""
	if sj:
		comb = _cstr(getattr(sj, "combination", None))
	else:
		for row in spr.shaft_jobs or []:
			if _cstr(_spr_job_id(row)) == jid:
				comb = _cstr(getattr(row, "combination", None))
				break

	bs = {
		"combination": comb or None,
		"rolls_per_bundle": no_of_packaging,
		"single_roll_gross_weight_kg": single_gross,
		"sticker_width": total_width_inch,
		"sticker_bundle_gross_weight_kg": round(whole_gross_kg, 2),
		"sticker_bundle_weight": bundle_net,
	}
	if frappe.get_meta("Bundle Stickers").has_field("job_id"):
		bs["job_id"] = jid or None
	spr.append("bundle_stickers", bs)
	spr.save(ignore_permissions=True)

	return {
		"single_roll_gross_kg": single_gross,
		"total_width_inch": total_width_inch,
		"sticker_bundle_weight_kg": bundle_net,
	}


def get_order_code(wo_doc):
	"""Party / order code for roll lines: WO custom fields, then Sales Order."""
	for attr in ("order_code", "custom_order_code", "custom_party_code"):
		v = getattr(wo_doc, attr, None)
		if v is not None and str(v).strip():
			return str(v).strip()
	so = getattr(wo_doc, "sales_order", None)
	if so:
		for col in ("custom_party_code", "po_no"):
			if frappe.db.has_column("Sales Order", col):
				v = frappe.db.get_value("Sales Order", so, col)
				if v is not None and str(v).strip():
					return str(v).strip()
		return str(so).strip()
	return ""
