import re

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import cint, flt, getdate

from production_entry.production_planning.doctype.planning_sheet.planning_sheet import (
	extract_quality_and_color,
)


def batch_shift_value(shift: str | None) -> str:
	if not shift:
		return ""
	s = shift.lower()
	if "night" in s:
		return "Night"
	if "day" in s:
		return "Day"
	return shift


def _cstr(v) -> str:
	return str(v).strip() if v is not None else ""


def _production_plan_custom_shaft_child_doctype() -> str | None:
	"""Child table Doctype behind Production Plan.custom_shaft_details (e.g. Shaft Plan Detail)."""
	try:
		pp_meta = frappe.get_meta("Production Plan")
	except Exception:
		return None
	for fname in ("custom_shaft_details", "custom_shaft_detail"):
		if not pp_meta.has_field(fname):
			continue
		f = pp_meta.get_field(fname)
		if f.fieldtype == "Table" and f.options:
			return f.options
	return None


def _looks_like_frappe_row_name(s: str) -> bool:
	"""Heuristic: autogenerated child row names are often long alphanumeric strings."""
	t = _cstr(s)
	if len(t) < 9:
		return False
	return t.isalnum()


def compute_produced_gsm(net_weight, width_inch, length_m) -> float:
	"""Roll line GSM from actuals: (net_weight * 10000) / (width_inch * length_m * 0.254)."""
	nw = flt(net_weight)
	w = flt(width_inch)
	ln = flt(length_m)
	den = w * ln * 0.254
	if den <= 0:
		return 0.0
	return round((nw * 10000.0) / den, 2)


def _work_order_names_for_pp_job(production_plan: str, m: dict, idx: int) -> str:
	"""Comma-separated WO names for this shaft row (matches WO resolution order)."""
	wo_key = m.get("production_plan_item") or m.get("job_id")
	wos = []
	if wo_key:
		wos = get_work_orders_for_job(production_plan, _cstr(wo_key))
	if not wos:
		ord_ppi = _ordered_production_plan_items(production_plan)
		if idx < len(ord_ppi):
			wos = get_work_orders_for_job(production_plan, ord_ppi[idx])
	return ", ".join(w["name"] for w in wos) if wos else ""


def _build_shaft_jobs_from_custom_shaft_details(production_plan: str) -> list[dict] | None:
	"""
	Load Available Jobs from Production Plan.custom_shaft_details (Table field on PP).
	Maps rows to Shaft Production Run Job; prefers human-readable Job column for job_id.
	"""
	child_dt = _production_plan_custom_shaft_child_doctype()
	if not child_dt or not frappe.db.exists("DocType", child_dt):
		return None
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return None
	pp_rows = frappe.db.sql(
		f"""
		SELECT * FROM `tab{child_dt}`
		WHERE parent = %(p)s
		ORDER BY idx ASC
		""",
		{"p": production_plan},
		as_dict=True,
	)
	if not pp_rows:
		return None
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out: list[dict] = []
	for idx, r in enumerate(pp_rows):
		m: dict = {}
		# Shaft Plan Detail: Job is field s_no (Int); also accept job / job_no / job_id
		readable = None
		if r.get("s_no") is not None and _cstr(r.get("s_no")) != "":
			try:
				readable = str(int(flt(r["s_no"])))
			except (TypeError, ValueError):
				readable = _cstr(r.get("s_no"))
		if not readable:
			readable = (
				_cstr(r.get("job"))
				if r.get("job") is not None and _cstr(r.get("job")) != ""
				else None
			)
		if not readable:
			readable = r.get("job_no") or r.get("job_id")
		if not readable or _cstr(readable) == "":
			readable = str(idx + 1)
		m["job_id"] = _cstr(readable)

		ppi = r.get("production_plan_item") or r.get("against_production_plan_item")
		if not ppi and _looks_like_frappe_row_name(_cstr(r.get("name", ""))):
			ppi = r.get("name")
		if ppi and job_meta.has_field("production_plan_item"):
			m["production_plan_item"] = _cstr(ppi)

		comb = r.get("shaft_combination") or r.get("combination")
		if comb is not None and job_meta.has_field("combination"):
			m["combination"] = comb

		# Map Shaft Plan Detail fieldnames: combined_width, meter__roll, no_of_shaft, total_weight_kgs
		field_aliases = {
			"gsm": ("gsm", "custom_gsm"),
			"quality": ("quality", "custom_quality"),
			"notes": ("notes", "custom_notes"),
			"total_width": (
				"combined_width",
				"total_width",
				"total_width_inches",
				"custom_total_width",
			),
			"meter_roll_mtrs": (
				"meter__roll",
				"meter_roll_mtrs",
				"meter_per_roll",
				"custom_meter_roll_mtrs",
			),
			"no_of_shafts": ("no_of_shafts", "no_of_shaft", "custom_no_of_shafts"),
			"net_weight": ("net_weight", "net_weight_per_shaft", "custom_net_weight_per_shaft"),
			"total_weight": ("total_weight_kgs", "total_weight", "custom_total_weight"),
			"custom_total_achieved_weight": ("custom_total_achieved_weight",),
			"party_code": ("party_code", "order_code", "custom_party_code"),
			"work_orders": ("work_orders", "custom_work_orders"),
		}
		for target, aliases in field_aliases.items():
			if not job_meta.has_field(target):
				continue
			for a in aliases:
				if a in r and r[a] is not None and _cstr(r[a]) != "":
					val = r[a]
					if target == "net_weight" and not isinstance(val, str):
						val = str(val)
					m[target] = val
					break

		if m.get("gsm") is not None and m.get("gsm") != "":
			try:
				m["gsm"] = int(flt(str(m["gsm"]).strip().split()[0]))
			except Exception:
				pass

		skip_copy = {
			"name",
			"owner",
			"creation",
			"modified",
			"modified_by",
			"docstatus",
			"idx",
			"parent",
			"parentfield",
			"parenttype",
			"doctype",
		}
		skip_alias = {
			"job",
			"job_no",
			"job_id",
			"s_no",
			"name",
			"production_plan_item",
			"against_production_plan_item",
			"shaft_combination",
			"combination",
			"combined_width",
			"meter__roll",
			"no_of_shaft",
			"total_weight_kgs",
		}
		for fn, v in r.items():
			if fn in skip_copy or fn in skip_alias or v is None:
				continue
			if not job_meta.has_field(fn):
				continue
			if fn not in m:
				if fn == "net_weight" and not isinstance(v, str):
					m[fn] = str(v)
				else:
					m[fn] = v

		jn = m.get("job_id")
		if jn and (not m.get("total_weight")):
			wo_key = m.get("production_plan_item") or jn
			tw = frappe.db.sql(
				"""
				SELECT IFNULL(SUM(qty), 0) FROM `tabWork Order`
				WHERE production_plan = %(pp)s AND production_plan_item = %(job)s AND docstatus < 2
				""",
				{"pp": production_plan, "job": _cstr(wo_key)},
			)[0][0]
			if flt(tw) <= 0:
				ord_ppi = _ordered_production_plan_items(production_plan)
				if idx < len(ord_ppi):
					tw = frappe.db.sql(
						"""
						SELECT IFNULL(SUM(qty), 0) FROM `tabWork Order`
						WHERE production_plan = %(pp)s AND production_plan_item = %(job)s AND docstatus < 2
						""",
						{"pp": production_plan, "job": _cstr(ord_ppi[idx])},
					)[0][0]
			if flt(tw) > 0:
				m["total_weight"] = flt(tw)

		if job_meta.has_field("work_orders"):
			m["work_orders"] = _work_order_names_for_pp_job(production_plan, m, idx)

		out.append(m)
	return out or None


def _ordered_production_plan_items(production_plan: str) -> list[str]:
	"""Distinct Work Order production_plan_item values in stable order (for ordinal WO fallback)."""
	rows = frappe.db.sql(
		"""
		SELECT wo.production_plan_item AS ppi, MIN(wo.creation) AS mc
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		  AND IFNULL(wo.production_plan_item, '') != ''
		GROUP BY wo.production_plan_item
		ORDER BY mc ASC, ppi ASC
		""",
		{"pp": production_plan},
		as_dict=True,
	)
	return [_cstr(r.ppi) for r in rows]


def _spr_job_row_index(spr_doc, job_row) -> int | None:
	rows = list(_spr_job_rows(spr_doc))
	for i, r in enumerate(rows):
		if getattr(r, "name", None) and getattr(job_row, "name", None) and r.name == job_row.name:
			return i
	jid = _cstr(_spr_job_id(job_row))
	for i, r in enumerate(rows):
		if _cstr(_spr_job_id(r)) == jid:
			return i
	return None


def _get_work_orders_for_spr_job(pp_name: str, spr_doc, job_row):
	"""Resolve Work Orders using production_plan_item, job_id, or ordinal row index."""
	meta = frappe.get_meta("Shaft Production Run Job")
	ppi = None
	if meta.has_field("production_plan_item"):
		ppi = getattr(job_row, "production_plan_item", None)
	if ppi:
		wos = get_work_orders_for_job(pp_name, _cstr(ppi))
		if wos:
			return wos
	jid = _spr_job_id(job_row)
	if jid:
		wos = get_work_orders_for_job(pp_name, _cstr(jid))
		if wos:
			return wos
	idx = _spr_job_row_index(spr_doc, job_row)
	if idx is not None:
		ord_ppi = _ordered_production_plan_items(pp_name)
		if 0 <= idx < len(ord_ppi):
			return get_work_orders_for_job(pp_name, ord_ppi[idx])
	return []


def _build_shaft_jobs_from_pp_details(production_plan: str) -> list[dict] | None:
	"""One row per Production Plan Shaft Detail line, field-aligned with Shaft Production Run Job."""
	if not production_plan or not frappe.db.exists("DocType", "Production Plan Shaft Detail"):
		return None
	if not frappe.db.exists("Production Plan", production_plan):
		return None
	pp_rows = frappe.db.sql(
		"""
		SELECT * FROM `tabProduction Plan Shaft Detail`
		WHERE parent = %(p)s
		ORDER BY idx ASC
		""",
		{"p": production_plan},
		as_dict=True,
	)
	if not pp_rows:
		return None
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out: list[dict] = []
	for r in pp_rows:
		m: dict = {}
		jn = r.get("job_no") or r.get("job_id")
		if not jn:
			continue
		m["job_id"] = _cstr(jn)
		if job_meta.has_field("production_plan_item"):
			m["production_plan_item"] = _cstr(jn)
		if r.get("shaft_combination") is not None and job_meta.has_field("combination"):
			m["combination"] = r.get("shaft_combination")
		for fn in (
			"gsm",
			"quality",
			"combination",
			"notes",
			"total_width",
			"meter_roll_mtrs",
			"net_weight",
			"total_weight",
			"custom_total_achieved_weight",
			"no_of_shafts",
			"party_code",
			"work_orders",
		):
			if fn in r and r[fn] is not None and job_meta.has_field(fn):
				m[fn] = r[fn]
		if (not m.get("total_weight")) and jn:
			tw = frappe.db.sql(
				"""
				SELECT IFNULL(SUM(qty), 0) FROM `tabWork Order`
				WHERE production_plan = %(pp)s AND production_plan_item = %(job)s AND docstatus < 2
				""",
				{"pp": production_plan, "job": _cstr(jn)},
			)[0][0]
			if flt(tw) > 0:
				m["total_weight"] = flt(tw)
		out.append(m)
	return out or None


class ShaftProductionRun(Document):
	def validate(self):
		self.calculate_produced_gsm()
		self.recalculate_job_achieved_weights()
		self.generate_batch_numbers()

	def recalculate_job_achieved_weights(self):
		"""Total Achieved Weight on each Available Jobs row = sum of net_weight in Roll Results for that job."""
		meta = frappe.get_meta("Shaft Production Run Job")
		if not meta.has_field("custom_total_achieved_weight"):
			return
		sums: dict[str, float] = {}
		for it in self.items or []:
			jid = _cstr(getattr(it, "job", None))
			if not jid:
				continue
			sums[jid] = sums.get(jid, 0.0) + flt(it.net_weight)
		for row in self.shaft_jobs or []:
			jid = _cstr(_spr_job_id(row))
			row.custom_total_achieved_weight = flt(sums.get(jid, 0.0))

	def calculate_produced_gsm(self):
		"""Set produced_gsm on each roll line from net weight, width (inch), length (m)."""
		meta = frappe.get_meta("Shaft Production Run Item")
		if not meta.has_field("produced_gsm"):
			return
		for row in self.items or []:
			row.produced_gsm = compute_produced_gsm(row.net_weight, row.width_inch, row.meter_roll)

	def on_submit(self):
		self.sync_batch_custom_fields()
		self.create_manufacturing_stock_entries()
		self.update_work_order_statuses()

	def on_cancel(self):
		self.cancel_manufacturing_stock_entries()

	def _unit_digit(self) -> int:
		u = (self.get("custom_unit") or "").strip()
		if not u:
			return 0
		m = re.search(r"(\d+)", u)
		return int(m.group(1)) if m else 0

	def generate_batch_numbers(self):
		"""Assign batch_no on each roll line when draft is saved (after Create Entry + required header fields).

		Format: ``{MM}{U}{YY}{S}/{N}`` — month (2) + unit digit + year (2) + shift suffix ``S`` + ``/`` + roll sequence ``N``.
		``tabBatch`` rows are created/updated on **submit** via ``sync_batch_custom_fields``, not on every save.
		"""
		if not self.run_date or not self.get("custom_unit") or not self.shift:
			return
		rows = [r for r in (self.items or []) if r.item_code]
		if not rows:
			return
		rd = getdate(self.run_date)
		unit_d = self._unit_digit()
		root_5 = f"{rd.month:02d}{unit_d}{rd.year % 100:02d}"
		series_prefix = self._resolve_series_prefix(root_5)
		next_roll = self._next_roll_starting(series_prefix)
		item_meta = frappe.get_meta("Shaft Production Run Item")
		for row in rows:
			if row.batch_no:
				continue
			row.batch_no = f"{series_prefix}/{next_roll}"
			if item_meta.has_field("roll_no"):
				rf = item_meta.get_field("roll_no")
				row.roll_no = int(next_roll) if rf and rf.fieldtype == "Int" else str(next_roll)
			if item_meta.has_field("custom_shift"):
				row.custom_shift = batch_shift_value(self.shift)
			next_roll += 1

	def _resolve_series_prefix(self, root_5: str) -> str:
		"""Reuse series for same run_date + shift + unit when batches already exist."""
		existing = frappe.db.sql(
			"""
			SELECT spi.batch_no
			FROM `tabShaft Production Run Item` spi
			INNER JOIN `tabShaft Production Run` spr ON spr.name = spi.parent
			WHERE spr.run_date = %(rd)s
			  AND spr.shift = %(sh)s
			  AND spr.custom_unit = %(un)s
			  AND spr.name != %(cur)s
			  AND IFNULL(spi.batch_no, '') != ''
			  AND spi.batch_no LIKE CONCAT(%(root)s, '%%')
			ORDER BY spr.modified DESC
			LIMIT 20
			""",
			{
				"rd": self.run_date,
				"sh": self.shift,
				"un": self.custom_unit,
				"cur": self.name or "",
				"root": root_5,
			},
		)
		for (bn,) in existing or []:
			if bn and "/" in bn:
				pref = bn.split("/")[0].strip()
				if pref.startswith(root_5) and len(pref) >= 6:
					return pref

		next_s = self._next_shift_suffix_num(root_5)
		return f"{root_5}{next_s}"

	def _next_shift_suffix_num(self, root_5: str) -> int:
		"""Pick next S digit(s) after scanning Batch + SPR items for this month/unit/year root."""
		max_s = 0
		rows = frappe.db.sql(
			"""
			SELECT batch_id FROM `tabBatch`
			WHERE batch_id LIKE CONCAT(%(root)s, '%%')
			""",
			{"root": root_5},
		)
		for (bid,) in rows or []:
			max_s = max(max_s, self._suffix_after_root(bid, root_5))
		rows2 = frappe.db.sql(
			"""
			SELECT spi.batch_no FROM `tabShaft Production Run Item` spi
			WHERE IFNULL(spi.batch_no,'') != ''
			  AND spi.batch_no LIKE CONCAT(%(root)s, '%%')
			""",
			{"root": root_5},
		)
		for (bn,) in rows2 or []:
			max_s = max(max_s, self._suffix_after_root(bn, root_5))
		return max_s + 1 if max_s >= 0 else 1

	def _suffix_after_root(self, batch_id: str, root_5: str) -> int:
		if not batch_id or "/" not in batch_id:
			return 0
		pref = batch_id.split("/", 1)[0].strip()
		if not pref.startswith(root_5):
			return 0
		s_part = pref[len(root_5) :]
		try:
			return int(s_part) if s_part else 0
		except ValueError:
			return 0

	def _next_roll_starting(self, series_prefix: str) -> int:
		mx = 0
		rows = frappe.db.sql(
			"""
			SELECT batch_id FROM `tabBatch`
			WHERE batch_id LIKE %(pat)s
			""",
			{"pat": f"{series_prefix}/%"},
		)
		for (bid,) in rows or []:
			mx = max(mx, self._roll_no_from_batch(bid, series_prefix))
		rows2 = frappe.db.sql(
			"""
			SELECT batch_no FROM `tabShaft Production Run Item`
			WHERE IFNULL(batch_no,'') != '' AND batch_no LIKE %(pat)s
			""",
			{"pat": f"{series_prefix}/%"},
		)
		for (bn,) in rows2 or []:
			mx = max(mx, self._roll_no_from_batch(bn, series_prefix))
		return mx + 1

	def _roll_no_from_batch(self, batch_id: str, series_prefix: str) -> int:
		if not batch_id or "/" not in batch_id:
			return 0
		pref, roll = batch_id.split("/", 1)
		if pref.strip() != series_prefix:
			return 0
		try:
			return int(roll.strip())
		except ValueError:
			return 0

	def sync_batch_custom_fields(self):
		batch_meta = frappe.get_meta("Batch")
		for row in self.items or []:
			if not row.batch_no or not frappe.db.exists("Batch", row.batch_no):
				continue
			data = {}
			if batch_meta.has_field("custom_gross_weight") and row.get("gross_weight") is not None:
				data["custom_gross_weight"] = flt(row.gross_weight)
			if batch_meta.has_field("custom_cbm") and row.get("custom_cbm") is not None:
				data["custom_cbm"] = flt(row.custom_cbm)
			if batch_meta.has_field("custom_diameter") and row.get("custom_diameter") is not None:
				data["custom_diameter"] = flt(row.custom_diameter)
			if batch_meta.has_field("custom_shift") and row.get("custom_shift"):
				data["custom_shift"] = row.custom_shift
			if batch_meta.has_field("custom_party_code_text") and row.get("custom_party_code_text"):
				data["custom_party_code_text"] = row.custom_party_code_text
			if not data:
				continue
			try:
				frappe.db.set_value("Batch", row.batch_no, data)
			except Exception:
				frappe.log_error(frappe.get_traceback(), "SPR Batch sync skipped")

	def _row_fg_qty(self, row) -> float:
		qty = flt(row.net_weight)
		if qty <= 0:
			qty = flt(row.gross_weight)
		return qty

	def _set_stock_entry_spr_link(self, se):
		meta = frappe.get_meta("Stock Entry")
		if meta.has_field("shaft_production_run"):
			se.shaft_production_run = self.name

	def create_manufacturing_stock_entries(self):
		"""One Stock Entry (Manufacture) per Work Order, same pattern as Roll Production Entry."""
		wo_groups = {}
		for row in self.items or []:
			wo_name = row.get("work_order") or row.get("wo_id")
			if not wo_name:
				continue
			wo_groups.setdefault(wo_name, []).append(row)

		created_entries = []

		for wo_id, rows in wo_groups.items():
			wo_doc = frappe.get_doc("Work Order", wo_id)
			total_qty = sum(self._row_fg_qty(r) for r in rows)

			if total_qty <= 0:
				frappe.msgprint(_("Skipping WO {0} — net/gross weight is 0").format(wo_id), alert=True)
				continue

			se = frappe.new_doc("Stock Entry")
			se.stock_entry_type = "Manufacture"
			se.work_order = wo_id
			se.production_item = wo_doc.production_item
			se.fg_completed_qty = total_qty
			se.from_bom = 1
			se.bom_no = wo_doc.bom_no
			se.use_multi_level_bom = wo_doc.use_multi_level_bom
			se.wip_warehouse = wo_doc.wip_warehouse
			se.to_warehouse = wo_doc.fg_warehouse

			self._set_stock_entry_spr_link(se)

			for row in rows:
				se.append(
					"items",
					{
						"item_code": row.item_code,
						"item_name": row.item_name,
						"qty": self._row_fg_qty(row),
						"uom": "Kg",
						"batch_no": row.batch_no,
						"serial_no": str(row.roll_no) if row.roll_no is not None else "",
						"t_warehouse": wo_doc.fg_warehouse,
						"is_finished_item": 1,
					},
				)

			se.get_items()

			se.insert()
			se.submit()
			created_entries.append(se.name)

			frappe.msgprint(
				_("Manufacturing Entry {0} created for WO {1}").format(se.name, wo_id),
				alert=True,
			)

		if created_entries:
			self.db_set("manufacturing_entries", ", ".join(created_entries))
			frappe.msgprint(
				_("Created {0} Manufacturing Entries: {1}").format(
					len(created_entries), ", ".join(created_entries)
				)
			)

	def update_work_order_statuses(self):
		wo_ids = list(
			{
				(row.get("work_order") or row.get("wo_id"))
				for row in (self.items or [])
				if row.get("work_order") or row.get("wo_id")
			}
		)
		for wo_id in wo_ids:
			wo_doc = frappe.get_doc("Work Order", wo_id)
			total_produced = frappe.db.sql(
				"""
				SELECT IFNULL(SUM(fg_completed_qty), 0)
				FROM `tabStock Entry`
				WHERE work_order = %s
				  AND stock_entry_type = 'Manufacture'
				  AND docstatus = 1
				""",
				wo_id,
			)[0][0]

			if flt(total_produced) >= flt(wo_doc.qty):
				wo_doc.db_set("status", "Completed")
				frappe.msgprint(_("Work Order {0} marked as Completed").format(wo_id), alert=True)

	def cancel_manufacturing_stock_entries(self):
		names = []
		if self.manufacturing_entries:
			names = [x.strip() for x in self.manufacturing_entries.split(",") if x.strip()]
		meta_se = frappe.get_meta("Stock Entry")
		if not names and meta_se.has_field("shaft_production_run"):
			conds = [
				"shaft_production_run = %s",
				"stock_entry_type = 'Manufacture'",
				"docstatus = 1",
			]
			params = [self.name]
			if meta_se.has_field("roll_production_entry"):
				conds.append("IFNULL(roll_production_entry, '') = ''")
			names = frappe.db.sql_list(
				f"SELECT name FROM `tabStock Entry` WHERE {' AND '.join(conds)}",
				params,
			)
		for name in names:
			if not frappe.db.exists("Stock Entry", name):
				continue
			if frappe.db.get_value("Stock Entry", name, "docstatus") != 1:
				continue
			se = frappe.get_doc("Stock Entry", name)
			se.cancel()
			frappe.msgprint(_("Cancelled Manufacturing Entry {0}").format(name), alert=True)
		self.db_set("manufacturing_entries", "")


@frappe.whitelist()
def get_production_plan_details(production_plan):
	"""Fill header fields from Production Plan."""
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return {}
	pp = frappe.get_doc("Production Plan", production_plan)
	pp_meta = frappe.get_meta("Production Plan")
	out = {
		"customer": pp.get("customer"),
		"custom_unit": pp.get("custom_unit"),
	}
	if pp_meta.has_field("custom_order_code") and pp.get("custom_order_code") is not None:
		out["custom_order_code"] = pp.get("custom_order_code")
	if pp_meta.has_field("custom_party_code") and pp.get("custom_party_code") not in (None, ""):
		out["custom_party_code"] = pp.get("custom_party_code")
	if pp.get("sales_order"):
		so = frappe.db.get_value(
			"Sales Order", pp.sales_order, ["customer", "transaction_date"], as_dict=True
		)
		if so:
			out["customer"] = out["customer"] or so.customer
	return out


@frappe.whitelist()
def get_production_plan_wo_summary(production_plan):
	"""Work Orders linked to this PP: status, order qty, pending qty — for desk popup after PP is set."""
	if not production_plan or not frappe.db.exists("Production Plan", production_plan):
		return []
	return frappe.db.sql(
		"""
		SELECT
			wo.name AS work_order,
			wo.status,
			IFNULL(wo.qty, 0) AS order_qty,
			GREATEST(0, IFNULL(wo.qty, 0) - IFNULL(wo.produced_qty, 0)) AS pending_qty
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		ORDER BY wo.name
		""",
		{"pp": production_plan},
		as_dict=True,
	)


def _count_combination_segments(combination) -> int:
	"""How many width slots in a combination string like '48\\" + 37\\" + ...'."""
	if not combination:
		return 1
	parts = [p.strip() for p in re.split(r"\+", str(combination)) if p.strip()]
	return max(1, len(parts))


def _parse_net_weight_kg_parts(net_weight) -> list[float]:
	"""Parse '89.61 + 6.2' style net weight from shaft job into kg numbers."""
	if not net_weight:
		return []
	s = str(net_weight).strip()
	if not s:
		return []
	out: list[float] = []
	for part in re.split(r"\s*\+\s*", s):
		part = part.strip()
		if not part:
			continue
		m = re.search(r"(\d+(?:\.\d+)?)", part.replace(",", ""))
		if m:
			out.append(flt(m.group(1)))
	return out


def _segment_weights_kg(job_row, segs: int) -> list[float]:
	"""Per-combination-segment kg; falls back to equal split of total target weight."""
	if segs < 1:
		segs = 1
	parts = _parse_net_weight_kg_parts(getattr(job_row, "net_weight", None))
	tw = flt(getattr(job_row, "total_weight", 0) or 0)
	if len(parts) >= segs:
		return [flt(x) for x in parts[:segs]]
	if parts:
		avg = sum(parts) / len(parts)
		while len(parts) < segs:
			parts.append(avg)
		return [flt(x) for x in parts[:segs]]
	if tw > 0:
		return [tw / segs] * segs
	return [0.0] * segs


def _planned_qty_for_roll_line(job_row, roll_index: int, segs: int) -> float:
	"""Planned qty = net weight (kg) for this combination segment (e.g. 48\"→89.61, 37\"→69.08)."""
	if segs < 1:
		segs = 1
	seg_weights = _segment_weights_kg(job_row, segs)
	seg_i = roll_index % segs
	seg_kg = seg_weights[seg_i] if seg_i < len(seg_weights) else 0.0
	return round(flt(seg_kg), 3)


@frappe.whitelist()
def get_next_spr_batch_numbers(
	shaft_production_run,
	count,
	client_max_roll=None,
	run_date=None,
	custom_unit=None,
	shift=None,
):
	"""
	Preview batch/roll numbers for new rows (e.g. after Create Entry) without submitting SPR.
	Requires run_date, custom_unit, shift. Optional client_max_roll = highest roll index already on the form.

	Pass run_date, custom_unit, shift from the desk form when the document is saved but header
	fields were just edited and not yet re-saved — otherwise get_doc() would see stale DB values.
	"""
	count = cint(count)
	if count < 1:
		return []
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save the Shaft Production Run first"))
	doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	if run_date not in (None, ""):
		doc.run_date = run_date
	if custom_unit not in (None, "") and str(custom_unit).strip():
		doc.custom_unit = custom_unit
	if shift not in (None, "") and str(shift).strip():
		doc.shift = shift
	rd_val = doc.run_date
	cu = _cstr(doc.get("custom_unit"))
	sh = _cstr(doc.shift)
	if not rd_val or not cu or not sh:
		frappe.throw(_("Set Run Date, Unit, and Shift to assign batch numbers."))
	rd = getdate(rd_val)
	unit_d = doc._unit_digit()
	root_5 = f"{rd.month:02d}{unit_d}{rd.year % 100:02d}"
	series_prefix = doc._resolve_series_prefix(root_5)
	next_roll = doc._next_roll_starting(series_prefix)
	try:
		if client_max_roll is not None and cint(client_max_roll) >= 0:
			next_roll = max(int(next_roll), cint(client_max_roll) + 1)
	except Exception:
		pass
	item_meta = frappe.get_meta("Shaft Production Run Item")
	out = []
	for _i in range(count):
		bn = f"{series_prefix}/{next_roll}"
		rf = item_meta.get_field("roll_no")
		rn = int(next_roll) if rf and rf.fieldtype == "Int" else str(next_roll)
		out.append({"batch_no": bn, "roll_no": rn})
		next_roll += 1
	return out


@frappe.whitelist()
def build_spr_roll_result_lines_for_job(shaft_production_run, job_id):
	"""
	Build Roll Production Result (SPR Item) lines for one job:
	rows = max(1, no_of_shafts × combination_segments), cycling Work Orders for that job.
	"""
	if not job_id:
		frappe.throw(_("Job ID is required"))
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save Shaft Production Run first"))
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Production Plan not found on this Shaft Production Run"))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	job_row = None
	for j in _spr_job_rows(spr_doc):
		if _cstr(_spr_job_id(j)) == _cstr(job_id):
			job_row = j
			break
	if not job_row:
		frappe.throw(_("Job {0} not found in Available Jobs").format(job_id))

	no_shafts = int(flt(getattr(job_row, "no_of_shafts", 0) or 0))
	if no_shafts < 1:
		no_shafts = 1
	comb = getattr(job_row, "combination", None) or ""
	segs = _count_combination_segments(comb)
	n_rolls = max(1, no_shafts * segs)

	shaft_combination = get_shaft_combination(pp_name, job_id)
	if getattr(job_row, "combination", None) and not shaft_combination:
		shaft_combination = job_row.combination

	wo_list = _get_work_orders_for_spr_job(pp_name, spr_doc, job_row)
	if not wo_list:
		frappe.throw(_("No Work Orders for job {0} on this Production Plan").format(job_id))

	lines = []
	for idx in range(n_rolls):
		wo = wo_list[idx % len(wo_list)]
		planned_qty = _planned_qty_for_roll_line(job_row, idx, segs)
		row = _spr_item_line_from_wo(pp_name, job_id, shaft_combination, planned_qty, wo)
		if getattr(job_row, "gsm", None) not in (None, 0, "0"):
			try:
				row["gsm"] = int(flt(job_row.gsm))
			except Exception:
				pass
		if getattr(job_row, "meter_roll_mtrs", None) not in (None, 0, ""):
			row["meter_roll"] = flt(job_row.meter_roll_mtrs)
		lines.append(row)
	return lines


@frappe.whitelist()
def get_job_rows_for_production_plan(production_plan):
	if not production_plan:
		return []
	if not frappe.db.exists("Production Plan", production_plan):
		frappe.throw(_("Production Plan {0} not found").format(production_plan))
	custom_sd = _build_shaft_jobs_from_custom_shaft_details(production_plan)
	if custom_sd is not None:
		return custom_sd
	detailed = _build_shaft_jobs_from_pp_details(production_plan)
	if detailed is not None:
		return detailed
	rows = frappe.db.sql(
		"""
		SELECT wo.production_plan_item AS job_no, SUM(wo.qty) AS total_weight
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp)s
		  AND wo.docstatus < 2
		  AND IFNULL(wo.production_plan_item, '') != ''
		GROUP BY wo.production_plan_item
		ORDER BY MIN(wo.creation)
		""",
		{"pp": production_plan},
		as_dict=True,
	)
	job_meta = frappe.get_meta("Shaft Production Run Job")
	out = []
	for r in rows:
		row = {"job_id": r.job_no, "total_weight": flt(r.total_weight)}
		if job_meta.has_field("production_plan_item"):
			row["production_plan_item"] = r.job_no
		out.append(row)
	return out


def _spr_job_rows(spr_doc):
	return getattr(spr_doc, "shaft_jobs", None) or getattr(spr_doc, "jobs", None) or []


def _spr_job_id(job):
	return getattr(job, "job_id", None) or getattr(job, "job_no", None)


def _spr_item_line_from_wo(pp_name, job_id, shaft_combination, planned_qty, wo):
	wo_doc = frappe.get_doc("Work Order", wo["name"])
	item_code = wo_doc.production_item
	item_name = frappe.db.get_value("Item", item_code, "item_name")
	gsm, width_inch = parse_item_code(item_code)
	quality, color = extract_quality_and_color(item_name or "")
	return {
		"work_order": wo["name"],
		"item_code": item_code,
		"item_name": item_name,
		"quality": quality or None,
		"gsm": gsm,
		"planned_qty": planned_qty,
		"job": job_id,
		"batch_no": "",
		"party_code": get_order_code(wo_doc),
		"roll_no": 0,
		"meter_roll": 0,
		"net_weight": 0,
		"gross_weight": 0,
		"width_inch": width_inch,
		"color": color or None,
	}


def _build_spr_items_from_pp(spr_doc, pp_name):
	items = []
	for job in _spr_job_rows(spr_doc):
		job_id = _spr_job_id(job)
		if not job_id:
			continue
		shaft_combination = get_shaft_combination(pp_name, job_id)
		if getattr(job, "combination", None) and not shaft_combination:
			shaft_combination = job.combination
		planned_qty = getattr(job, "total_weight", None) or 0
		for wo in _get_work_orders_for_spr_job(pp_name, spr_doc, job):
			items.append(_spr_item_line_from_wo(pp_name, job_id, shaft_combination, planned_qty, wo))
	return items


def _build_roll_items_from_spr(spr_doc, pp_name, job_id_filter=None):
	items = []
	for job in _spr_job_rows(spr_doc):
		job_id = _spr_job_id(job)
		if not job_id:
			continue
		if job_id_filter is not None and _cstr(job_id) != _cstr(job_id_filter):
			continue
		shaft_combination = get_shaft_combination(pp_name, job_id)
		if getattr(job, "combination", None) and not shaft_combination:
			shaft_combination = job.combination
		planned_qty = getattr(job, "total_weight", None) or 0
		for wo in _get_work_orders_for_spr_job(pp_name, spr_doc, job):
			wo_doc = frappe.get_doc("Work Order", wo["name"])
			item_code = wo_doc.production_item
			item_name = frappe.db.get_value("Item", item_code, "item_name")
			gsm, width_inch = parse_item_code(item_code)
			items.append(
				{
					"job_no": job_id,
					"shaft_combination": shaft_combination,
					"planned_qty": planned_qty,
					"wo_id": wo["name"],
					"item_code": item_code,
					"item_name": item_name,
					"gsm": gsm,
					"width_inches": width_inch,
					"order_code": get_order_code(wo_doc),
					"batch_no": "",
					"roll_no": "",
					"meter_per_roll": 0,
					"net_weight": 0,
					"gross_weight": 0,
				}
			)
	return items


@frappe.whitelist()
def get_item_rows_for_production_plan(production_plan):
	"""Build SPR Item rows from WOs for all jobs (API / legacy). Desk flow uses build_spr_roll_result_lines_for_job per job."""
	if not production_plan:
		return []
	jobs = get_job_rows_for_production_plan(production_plan)
	spr = frappe._dict(shaft_jobs=[])
	for j in jobs:
		spr.shaft_jobs.append(frappe._dict(job_id=j["job_id"], total_weight=j.get("total_weight")))
	return _build_spr_items_from_pp(spr, production_plan)


@frappe.whitelist()
def get_or_create_roll_entry(shaft_production_run):
	"""All jobs on SPR (legacy API). Prefer get_or_create_roll_entry_for_job from shaft_jobs row."""
	existing = frappe.db.get_value(
		"Roll Production Entry",
		{"shaft_production_run": shaft_production_run, "docstatus": ["!=", 2]},
		"name",
	)
	if existing:
		return {"existing": existing}
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Could not find Production Plan linked to {0}").format(shaft_production_run))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	items = _build_roll_items_from_spr(spr_doc, pp_name)
	return {"production_plan": pp_name, "items": items}


@frappe.whitelist()
def get_or_create_roll_entry_for_job(shaft_production_run, job_id):
	"""Open/create Roll Production Entry for a single PP job (shaft + combination from shaft_jobs row)."""
	if not job_id:
		frappe.throw(_("Job ID is required"))
	if not shaft_production_run or not frappe.db.exists("Shaft Production Run", shaft_production_run):
		frappe.throw(_("Save Shaft Production Run first"))
	meta_rpe = frappe.get_meta("Roll Production Entry")
	filters = {
		"shaft_production_run": shaft_production_run,
		"docstatus": ["!=", 2],
	}
	if meta_rpe.has_field("job_id"):
		filters["job_id"] = _cstr(job_id)
	existing = frappe.db.get_value("Roll Production Entry", filters, "name")
	if existing:
		return {"existing": existing, "job_id": _cstr(job_id)}
	pp_name = get_pp_from_spr(shaft_production_run)
	if not pp_name:
		frappe.throw(_("Could not find Production Plan linked to {0}").format(shaft_production_run))
	spr_doc = frappe.get_doc("Shaft Production Run", shaft_production_run)
	items = _build_roll_items_from_spr(spr_doc, pp_name, job_id_filter=job_id)
	if not items:
		frappe.throw(
			_("No roll lines for job {0}. Check Work Orders for this Production Plan.").format(job_id)
		)
	return {
		"production_plan": pp_name,
		"items": items,
		"job_id": _cstr(job_id),
	}


def get_pp_from_spr(spr_name):
	pp_field = frappe.db.get_value("Shaft Production Run", spr_name, "production_plan")
	if pp_field:
		return pp_field
	if spr_name.startswith("SPR-"):
		return spr_name[4:]
	return None


def get_shaft_combination(pp_name, job_no):
	if frappe.db.exists("DocType", "Production Plan Shaft Detail"):
		v = frappe.db.get_value(
			"Production Plan Shaft Detail",
			{"parent": pp_name, "job_no": job_no},
			"shaft_combination",
		)
		if v:
			return v
	child_dt = _production_plan_custom_shaft_child_doctype()
	if child_dt:
		meta_child = frappe.get_meta(child_dt)
		if meta_child.has_field("s_no"):
			s_no_candidates = [job_no]
			try:
				s_no_candidates.append(cint(job_no))
			except Exception:
				pass
			for candidate in s_no_candidates:
				if candidate is None or candidate == "":
					continue
				v = frappe.db.get_value(child_dt, {"parent": pp_name, "s_no": candidate}, "combination")
				if v:
					return v
		for jf in ("job", "job_no", "job_id"):
			if not meta_child.has_field(jf):
				continue
			v = frappe.db.get_value(child_dt, {"parent": pp_name, jf: job_no}, "shaft_combination")
			if v:
				return v
			if meta_child.has_field("combination"):
				v = frappe.db.get_value(child_dt, {"parent": pp_name, jf: job_no}, "combination")
				if v:
					return v
	return ""


def get_work_orders_for_job(pp_name, job_no):
	return frappe.db.sql(
		"""
		SELECT wo.name, wo.production_item, wo.qty as planned_qty, wo.produced_qty, wo.status
		FROM `tabWork Order` wo
		WHERE wo.production_plan = %(pp_name)s
		  AND wo.production_plan_item = %(job_no)s
		  AND wo.docstatus != 2
		ORDER BY wo.name
		""",
		{"pp_name": pp_name, "job_no": job_no},
		as_dict=True,
	)


def parse_item_code(item_code):
	try:
		if len(item_code) >= 16:
			gsm = int(item_code[9:12])
			width_mm = int(item_code[12:16])
			width_inch = round(width_mm / 25.4, 1)
			return gsm, width_inch
	except Exception:
		pass
	return 0, 0


def get_order_code(wo_doc):
	return getattr(wo_doc, "order_code", None) or getattr(wo_doc, "sales_order", None) or ""
